import 'terroir_node.dart';

class TerroirCatalog {
  static const List<TerroirNode> defaultNodes = [
    // CONTINENTS
    TerroirNode(
      id: 'cont_europe',
      name: 'Europe',
      level: TerroirLevel.continent,
      flagEmoji: '🇪🇺',
      icon: '🏰',
      description: 'Le berceau historique de la viticulture mondiale et des plus grands crus.',
    ),
    TerroirNode(
      id: 'cont_americas',
      name: 'Amériques',
      level: TerroirLevel.continent,
      flagEmoji: '🌎',
      icon: '🌄',
      description: 'Des vallées californiennes aux altitudes andines de Mendoza.',
    ),
    TerroirNode(
      id: 'cont_oceania',
      name: 'Océanie',
      level: TerroirLevel.continent,
      flagEmoji: '🌏',
      icon: '🦘',
      description: 'Terroirs solaires et maritimes d\'Australie et de Nouvelle-Zélande.',
    ),
    TerroirNode(
      id: 'cont_africa',
      name: 'Afrique',
      level: TerroirLevel.continent,
      flagEmoji: '🌍',
      icon: '🦁',
      description: 'Cap occidental, Stellenbosch et vignobles côtiers sud-africains.',
    ),
    TerroirNode(
      id: 'cont_asia',
      name: 'Asie & Moyen-Orient',
      level: TerroirLevel.continent,
      flagEmoji: '🏯',
      icon: '🏺',
      description: 'Vignobles antiques du Caucase (Géorgie), Liban et essor du Ningxia.',
    ),

    // COUNTRIES
    TerroirNode(
      id: 'country_fr',
      name: 'France',
      parentName: 'Europe',
      level: TerroirLevel.country,
      flagEmoji: '🇫🇷',
      icon: '🍷',
      description: 'Bordeaux, Bourgogne, Champagne, Vallée du Rhône, Loire...',
    ),
    TerroirNode(
      id: 'country_it',
      name: 'Italie',
      parentName: 'Europe',
      level: TerroirLevel.country,
      flagEmoji: '🇮🇹',
      icon: '🍕',
      description: 'Toscane, Piémont, Vénétie, Sicile, Barolo, Brunello...',
    ),
    TerroirNode(
      id: 'country_es',
      name: 'Espagne',
      parentName: 'Europe',
      level: TerroirLevel.country,
      flagEmoji: '🇪🇸',
      icon: '💃',
      description: 'Rioja, Ribera del Duero, Priorat, Rías Baixas, Cava...',
    ),
    TerroirNode(
      id: 'country_us',
      name: 'États-Unis',
      parentName: 'Amériques',
      level: TerroirLevel.country,
      flagEmoji: '🇺🇸',
      icon: '🦅',
      description: 'Napa Valley, Sonoma, Willamette Valley, Columbia Valley...',
    ),
    TerroirNode(
      id: 'country_ar',
      name: 'Argentine',
      parentName: 'Amériques',
      level: TerroirLevel.country,
      flagEmoji: '🇦🇷',
      icon: '🏔️',
      description: 'Mendoza, Uco Valley, Salta, Patagonie (Malbec, Torrontés)...',
    ),
    TerroirNode(
      id: 'country_cl',
      name: 'Chili',
      parentName: 'Amériques',
      level: TerroirLevel.country,
      flagEmoji: '🇨🇱',
      icon: '🦙',
      description: 'Valle del Maipo, Colchagua, Casablanca (Carménère, Cabernet)...',
    ),
    TerroirNode(
      id: 'country_au',
      name: 'Australie',
      parentName: 'Océanie',
      level: TerroirLevel.country,
      flagEmoji: '🇦🇺',
      icon: '☀️',
      description: 'Barossa Valley, Margaret River, McLaren Vale, Hunter Valley...',
    ),
    TerroirNode(
      id: 'country_nz',
      name: 'Nouvelle-Zélande',
      parentName: 'Océanie',
      level: TerroirLevel.country,
      flagEmoji: '🇳🇿',
      icon: '🥝',
      description: 'Marlborough, Central Otago, Hawke\'s Bay...',
    ),
    TerroirNode(
      id: 'country_za',
      name: 'Afrique du Sud',
      parentName: 'Afrique',
      level: TerroirLevel.country,
      flagEmoji: '🇿🇦',
      icon: '🍇',
      description: 'Stellenbosch, Franschhoek, Swartland (Chenin, Pinotage)...',
    ),
    TerroirNode(
      id: 'country_de',
      name: 'Allemagne',
      parentName: 'Europe',
      level: TerroirLevel.country,
      flagEmoji: '🇩🇪',
      icon: '🏰',
      description: 'Mosel, Rheingau, Pfalz, Baden (Riesling, Spätburgunder)...',
    ),
    TerroirNode(
      id: 'country_pt',
      name: 'Portugal',
      parentName: 'Europe',
      level: TerroirLevel.country,
      flagEmoji: '🇵🇹',
      icon: '⛵',
      description: 'Douro, Alentejo, Vinho Verde, Dão, Porto, Madère...',
    ),

    // REGIONS
    TerroirNode(
      id: 'reg_bordeaux',
      name: 'Bordeaux',
      parentName: 'France',
      level: TerroirLevel.region,
      flagEmoji: '🇫🇷',
      icon: '🏰',
      description: 'Rive Gauche & Rive Droite, berceau des Grands Crus Classés 1855.',
    ),
    TerroirNode(
      id: 'reg_bourgogne',
      name: 'Bourgogne',
      parentName: 'France',
      level: TerroirLevel.region,
      flagEmoji: '🇫🇷',
      icon: '🍇',
      description: 'Climats classés à l\'UNESCO, Pinot Noir et Chardonnay d\'orfèvre.',
    ),
    TerroirNode(
      id: 'reg_rhone',
      name: 'Vallée du Rhône',
      parentName: 'France',
      level: TerroirLevel.region,
      flagEmoji: '🇫🇷',
      icon: '🌞',
      description: 'Syrah septentrionale et assemblages solaires méridionaux.',
    ),
    TerroirNode(
      id: 'reg_champagne',
      name: 'Champagne',
      parentName: 'France',
      level: TerroirLevel.region,
      flagEmoji: '🇫🇷',
      icon: '🍾',
      description: 'L\'effervescence royale de la craie champenoise.',
    ),
    TerroirNode(
      id: 'reg_loire',
      name: 'Val de Loire',
      parentName: 'France',
      level: TerroirLevel.region,
      flagEmoji: '🇫🇷',
      icon: '🏰',
      description: 'Sancerre, Saumur-Champigny, Vouvray et Muscadet.',
    ),
    TerroirNode(
      id: 'reg_alsace',
      name: 'Alsace',
      parentName: 'France',
      level: TerroirLevel.region,
      flagEmoji: '🇫🇷',
      icon: '🥨',
      description: 'Riesling, Gewurztraminer et Pinot Gris de grands terroirs gréseux.',
    ),
    TerroirNode(
      id: 'reg_toscane',
      name: 'Toscane',
      parentName: 'Italie',
      level: TerroirLevel.region,
      flagEmoji: '🇮🇹',
      icon: '🌻',
      description: 'Sangiovese, collines du Chianti, Brunello et Super-Toscans.',
    ),
    TerroirNode(
      id: 'reg_piemont',
      name: 'Piémont',
      parentName: 'Italie',
      level: TerroirLevel.region,
      flagEmoji: '🇮🇹',
      icon: '👑',
      description: 'Nebbiolo, brumes des Langhe, Barolo et Barbaresco.',
    ),
    TerroirNode(
      id: 'reg_rioja',
      name: 'Rioja',
      parentName: 'Espagne',
      level: TerroirLevel.region,
      flagEmoji: '🇪🇸',
      icon: '🍷',
      description: 'Tempranillo élevé en fûts de chêne, Gran Reserva et Alta.',
    ),
    TerroirNode(
      id: 'reg_napa',
      name: 'Napa Valley',
      parentName: 'États-Unis',
      level: TerroirLevel.region,
      flagEmoji: '🇺🇸',
      icon: '🌉',
      description: 'Cabernet Sauvignon d\'anthologie, Oakville, Rutherford.',
    ),
    TerroirNode(
      id: 'reg_douro',
      name: 'Vallée du Douro',
      parentName: 'Portugal',
      level: TerroirLevel.region,
      flagEmoji: '🇵🇹',
      icon: '⛵',
      description: 'Coteaux de schiste du fleuve Douro, Touriga Nacional et grands Portos.',
    ),
    TerroirNode(
      id: 'reg_vinho_verde',
      name: 'Vinho Verde',
      parentName: 'Portugal',
      level: TerroirLevel.region,
      flagEmoji: '🇵🇹',
      icon: '🌊',
      description: 'Alvarinho et Loureiro océaniques sur arènes granitiques du Minho.',
    ),
    TerroirNode(
      id: 'reg_mosel',
      name: 'Mosel (Moselle)',
      parentName: 'Allemagne',
      level: TerroirLevel.region,
      flagEmoji: '🇩🇪',
      icon: '🏰',
      description: 'Rieslings minéraux d\'anthologie sur coteaux abrupts de schistes bleus.',
    ),
    TerroirNode(
      id: 'reg_wachau',
      name: 'Wachau',
      parentName: 'Autriche',
      level: TerroirLevel.region,
      flagEmoji: '🇦🇹',
      icon: '🏔️',
      description: 'Grüner Veltliner Smaragd et Rieslings sur terrasses de gneiss du Danube.',
    ),
    TerroirNode(
      id: 'reg_sonoma',
      name: 'Sonoma County',
      parentName: 'États-Unis',
      level: TerroirLevel.region,
      flagEmoji: '🇺🇸',
      icon: '🌲',
      description: 'Russian River Valley Pinot Noir & Chardonnay, Zinfandel de Dry Creek.',
    ),
    TerroirNode(
      id: 'reg_willamette',
      name: 'Willamette Valley',
      parentName: 'États-Unis',
      level: TerroirLevel.region,
      flagEmoji: '🇺🇸',
      icon: '🦫',
      description: 'Pinot Noir et Chardonnay bourguignons sur terres rouges volcaniques Jory.',
    ),
    TerroirNode(
      id: 'reg_valle_de_uco',
      name: 'Valle de Uco',
      parentName: 'Argentine',
      level: TerroirLevel.region,
      flagEmoji: '🇦🇷',
      icon: '🏔️',
      description: 'Gualtallary, Paraje Altamira — Malbec d\'altitude à 1400m au pied des Andes.',
    ),
    TerroirNode(
      id: 'reg_maipo',
      name: 'Valle del Maipo',
      parentName: 'Chili',
      level: TerroirLevel.region,
      flagEmoji: '🇨🇱',
      icon: '🇨🇱',
      description: 'Puente Alto — Cabernet Sauvignon aristocratique et Carmenère d\'Apalta.',
    ),
    TerroirNode(
      id: 'reg_barossa',
      name: 'Barossa Valley',
      parentName: 'Australie',
      level: TerroirLevel.region,
      flagEmoji: '🇦🇺',
      icon: '🦘',
      description: 'Shiraz centenaires préphylloxériques, concentration et richesse absolue.',
    ),
    TerroirNode(
      id: 'reg_marlborough',
      name: 'Marlborough',
      parentName: 'Nouvelle-Zélande',
      level: TerroirLevel.region,
      flagEmoji: '🇳🇿',
      icon: '🥝',
      description: 'Sauvignon Blanc éclatant de thiols, fruits de la passion et groseille.',
    ),
    TerroirNode(
      id: 'reg_stellenbosch',
      name: 'Stellenbosch',
      parentName: 'Afrique du Sud',
      level: TerroirLevel.region,
      flagEmoji: '🇿🇦',
      icon: '🦁',
      description: 'Sols de granites décomposés, grands Cabernets et Pinotages nobles.',
    ),

    // APPELLATIONS
    TerroirNode(
      id: 'app_pauillac',
      name: 'Pauillac',
      parentName: 'Bordeaux',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '🏰',
      description: 'Latour, Lafite, Mouton Rothschild — puissance et noblesse du Cabernet.',
    ),
    TerroirNode(
      id: 'app_margaux',
      name: 'Margaux',
      parentName: 'Bordeaux',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '🌹',
      description: 'Château Margaux, Palmer — élégance soyeuse et bouquet floral inimitable.',
    ),
    TerroirNode(
      id: 'app_saint_julien',
      name: 'Saint-Julien',
      parentName: 'Bordeaux',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '⚖️',
      description: 'Ducru-Beaucaillou, Léoville — l\'équilibre parfait du Médoc.',
    ),
    TerroirNode(
      id: 'app_saint_emilion',
      name: 'Saint-Émilion Grand Cru',
      parentName: 'Bordeaux',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '⛪',
      description: 'Plateau calcaire, Cheval Blanc, Ausone — velouté du Merlot.',
    ),
    TerroirNode(
      id: 'app_pomerol',
      name: 'Pomerol',
      parentName: 'Bordeaux',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '💎',
      description: 'Petrus, Le Pin — argiles bleues et opulence légendaire.',
    ),
    TerroirNode(
      id: 'app_vosne_romanee',
      name: 'Vosne-Romanée',
      parentName: 'Bourgogne',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '👑',
      description: 'Romanée-Conti, La Tâche, Richebourg — le joyau suprême du Pinot Noir.',
    ),
    TerroirNode(
      id: 'app_gevrey_chambertin',
      name: 'Gevrey-Chambertin',
      parentName: 'Bourgogne',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '🛡️',
      description: 'Le roi des vins de Bourgogne, puissance tannique et sous-bois.',
    ),
    TerroirNode(
      id: 'app_meursault',
      name: 'Meursault',
      parentName: 'Bourgogne',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '🧈',
      description: 'Chardonnay beurré, noisette grillée et minéralité envoûtante.',
    ),
    TerroirNode(
      id: 'app_chateauneuf',
      name: 'Châteauneuf-du-Pape',
      parentName: 'Vallée du Rhône',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '🏰',
      description: 'Galets roulés, 13 cépages, épices douces et puissance généreuse.',
    ),
    TerroirNode(
      id: 'app_cote_rotie',
      name: 'Côte-Rôtie',
      parentName: 'Vallée du Rhône',
      level: TerroirLevel.appellation,
      flagEmoji: '🇫🇷',
      icon: '⛰️',
      description: 'Pentes abruptes de schiste, Syrah parfumée d\'une touche de Viognier.',
    ),
    TerroirNode(
      id: 'app_barolo',
      name: 'Barolo DOCG',
      parentName: 'Piémont',
      level: TerroirLevel.appellation,
      flagEmoji: '🇮🇹',
      icon: '👑',
      description: 'Le roi des vins et le vin des rois en Italie, truffe et goudron noble.',
    ),
    TerroirNode(
      id: 'app_brunello',
      name: 'Brunello di Montalcino',
      parentName: 'Toscane',
      level: TerroirLevel.appellation,
      flagEmoji: '🇮🇹',
      icon: '🍇',
      description: '100% Sangiovese Grosso vieilli longuement en grands foudres de chêne.',
    ),
    TerroirNode(
      id: 'app_porto_vintage',
      name: 'Porto Vintage',
      parentName: 'Vallée du Douro',
      level: TerroirLevel.appellation,
      flagEmoji: '🇵🇹',
      icon: '⛵',
      description: 'Millésime d\'exception muté à l\'eau-de-vie, puissance de garde centenaire.',
    ),
    TerroirNode(
      id: 'app_mosel_kabinett',
      name: 'Mosel Kabinett',
      parentName: 'Mosel (Moselle)',
      level: TerroirLevel.appellation,
      flagEmoji: '🇩🇪',
      icon: '🏰',
      description: 'Riesling aérien à faible degré d\'alcool et tension minérale incomparable.',
    ),
    TerroirNode(
      id: 'app_oakville',
      name: 'Oakville AVA',
      parentName: 'Napa Valley',
      level: TerroirLevel.appellation,
      flagEmoji: '🇺🇸',
      icon: '🌟',
      description: 'Opus One, To Kalon Vineyard — le coeur palpitant du Cabernet de Napa.',
    ),
  ];
}
