import 'wine_world_model.dart';

/// Espagne et Portugal.
///
/// Deux pays où le RANG compte plus qu'ailleurs : la hiérarchie espagnole
/// (Joven, Crianza, Reserva, Gran Reserva) est inscrite sur l'étiquette et change la
/// longévité du simple au triple.
const List<RegionVin> regionsIberie = [
  // ═══════════════ ESPAGNE ═══════════════
  RegionVin(
    id: 'es_rioja',
    pays: 'Espagne',
    nom: 'Rioja',
    elevages: {'red': Elevage(ContenantElevage.barrique, 12, impose: true)},
    alias: ['rioja', 'rioja alta', 'rioja alavesa', 'rioja oriental'],
    cepages: ['Tempranillo', 'Garnacha', 'Graciano'],
    longevites: {
      'red': AgingProfile(id: 'rioja_rouge', libelle: 'Rioja',
          debut: 3, picDebut: 6, picFin: 14, fin: 20),
      'white': AgingProfile(id: 'rioja_blanc', libelle: 'Rioja blanc',
          debut: 1, picDebut: 3, picFin: 10, fin: 15),
    },
    references: [
      ReferenceVin(nom: 'R. López de Heredia', alias: ['lopez de heredia', 'tondonia'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'tondonia', libelle: 'Tondonia',
              debut: 8, picDebut: 15, picFin: 40, fin: 60),
          elevage: Elevage(ContenantElevage.barrique, 72)),
      ReferenceVin(nom: 'La Rioja Alta', alias: ['rioja alta 890', 'vina ardanza']),
      ReferenceVin(nom: 'Marqués de Murrieta', alias: ['murrieta', 'castillo ygay']),
      ReferenceVin(nom: 'CVNE', alias: ['imperial', 'cune']),
      ReferenceVin(nom: 'Marqués de Riscal', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Campo Viejo', raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Faustino', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'es_ribera',
    pays: 'Espagne',
    nom: 'Ribera del Duero & Duero',
    elevages: {'red': Elevage(ContenantElevage.barrique, 12, impose: true)},
    alias: ['ribera del duero', 'toro', 'rueda', 'cigales'],
    cepages: ['Tempranillo', 'Verdejo'],
    longevites: {
      'red': AgingProfile(id: 'ribera_rouge', libelle: 'Ribera del Duero',
          debut: 3, picDebut: 7, picFin: 16, fin: 22),
      'white': AgingProfile(id: 'rueda', libelle: 'Rueda',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
    },
    references: [
      ReferenceVin(nom: 'Vega Sicilia', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'vega_sicilia', libelle: 'Vega Sicilia Único',
              debut: 10, picDebut: 20, picFin: 45, fin: 60),
          elevage: Elevage(ContenantElevage.barrique, 72)),
      ReferenceVin(nom: 'Pingus',
          longevite: AgingProfile(id: 'pingus', libelle: 'Pingus',
              debut: 6, picDebut: 12, picFin: 30, fin: 45)),
      ReferenceVin(nom: 'Pesquera'),
      ReferenceVin(nom: 'Protos', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'es_priorat',
    pays: 'Espagne',
    nom: 'Priorat & Montsant',
    elevages: {'red': Elevage(ContenantElevage.barrique, 14)},
    alias: ['priorat', 'montsant'],
    cepages: ['Garnacha', 'Cariñena'],
    longevites: {'red': AgingProfile(id: 'priorat', libelle: 'Priorat',
        debut: 4, picDebut: 8, picFin: 18, fin: 26)},
    references: [
      ReferenceVin(nom: 'Clos Mogador'),
      ReferenceVin(nom: 'Álvaro Palacios', alias: ['alvaro palacios', 'l\'ermita']),
    ],
  ),
  RegionVin(
    id: 'es_monastrell',
    pays: 'Espagne',
    nom: 'Levant — Jumilla, Yecla, Alicante',
    elevages: {'red': Elevage(ContenantElevage.barrique, 18)},
    alias: ['jumilla', 'yecla', 'alicante', 'bullas', 'almansa'],
    cepages: ['Monastrell'],
    longevites: {'red': AgingProfile(id: 'jumilla', libelle: 'Monastrell du Levant',
        debut: 2, picDebut: 5, picFin: 12, fin: 16)},
    references: [
      ReferenceVin(nom: 'Bodegas El Nido', alias: ['el nido', 'clio'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'clio', libelle: 'El Nido Clio',
              debut: 3, picDebut: 6, picFin: 14, fin: 18)),
      ReferenceVin(nom: 'Juan Gil', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'es_galice',
    pays: 'Espagne',
    nom: 'Galice & Atlantique',
    elevages: {'white': Elevage(ContenantElevage.inox, 6)},
    alias: ['rias baixas', 'albarino', 'godello', 'valdeorras', 'ribeiro',
      'ribeira sacra', 'bierzo'],
    cepages: ['Albariño', 'Godello', 'Mencía'],
    longevites: {
      'white': AgingProfile(id: 'albarino', libelle: 'Albariño & Godello',
          debut: 1, picDebut: 2, picFin: 7, fin: 10),
      'red': AgingProfile(id: 'mencia', libelle: 'Mencía',
          debut: 2, picDebut: 4, picFin: 11, fin: 16),
    },
    references: [
      ReferenceVin(nom: 'Pazo de Señorans', alias: ['pazo de senorans']),
      ReferenceVin(nom: 'Descendientes de J. Palacios', alias: ['corullon']),
    ],
  ),
  RegionVin(
    id: 'es_catalogne',
    pays: 'Espagne',
    nom: 'Catalogne & Cava',
    elevages: {'sparkling': Elevage(ContenantElevage.bouteille, 9, impose: true)},
    alias: ['penedes', 'cava', 'emporda', 'terra alta', 'conca de barbera'],
    cepages: ['Macabeo', 'Xarel·lo', 'Parellada'],
    longevites: {
      'sparkling': AgingProfile(id: 'cava', libelle: 'Cava',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
      'red': AgingProfile(id: 'penedes_rouge', libelle: 'Penedès rouge',
          debut: 1, picDebut: 3, picFin: 9, fin: 13),
      'white': AgingProfile(id: 'penedes_blanc', libelle: 'Penedès blanc',
          debut: 0, picDebut: 1, picFin: 4, fin: 7),
    },
    references: [
      ReferenceVin(nom: 'Familia Torres', alias: ['torres'],
          raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Freixenet', raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Codorníu', alias: ['codorniu'],
          raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Recaredo'),
    ],
  ),
  RegionVin(
    id: 'es_jerez',
    pays: 'Espagne',
    nom: 'Jerez & Montilla',
    elevages: {'*': Elevage(ContenantElevage.barrique, 36, impose: true)},
    alias: ['jerez', 'sherry', 'xeres', 'manzanilla', 'montilla',
      'fino', 'amontillado', 'oloroso', 'palo cortado'],
    cepages: ['Palomino', 'Pedro Ximénez'],
    longevites: {'*': AgingProfile(id: 'jerez', libelle: 'Jerez',
        debut: 0, picDebut: 2, picFin: 20, fin: 40)},
    references: [
      ReferenceVin(nom: 'González Byass', alias: ['gonzalez byass', 'tio pepe'],
          raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Equipo Navazos'),
      ReferenceVin(nom: 'Lustau', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'es_castille',
    pays: 'Espagne',
    nom: 'Castille & Manche',
    alias: ['la mancha', 'valdepenas', 'carinena', 'calatayud', 'campo de borja',
      'somontano', 'navarra'],
    cepages: ['Tempranillo', 'Garnacha'],
    longevites: {'red': AgingProfile(id: 'mancha', libelle: 'Castille rouge',
        debut: 1, picDebut: 3, picFin: 8, fin: 12)},
  ),

  // ═══════════════ PORTUGAL ═══════════════
  RegionVin(
    id: 'pt_porto',
    pays: 'Portugal',
    nom: 'Porto',
    elevages: {'*': Elevage(ContenantElevage.foudre, 24)},
    alias: ['porto', 'port', 'vintage port', 'tawny', 'lbv', 'colheita'],
    cepages: ['Touriga Nacional', 'Touriga Franca', 'Tinta Roriz'],
    longevites: {'*': AgingProfile(id: 'porto', libelle: 'Porto',
        debut: 1, picDebut: 5, picFin: 25, fin: 40)},
    references: [
      ReferenceVin(nom: 'Taylor\'s', alias: ['taylors', 'taylor fladgate'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'taylor_vintage', libelle: 'Taylor Vintage',
              debut: 8, picDebut: 20, picFin: 45, fin: 70),
          elevage: Elevage(ContenantElevage.foudre, 24)),
      ReferenceVin(nom: 'Quinta do Noval', alias: ['noval', 'nacional']),
      ReferenceVin(nom: 'Graham\'s', alias: ['grahams'],
          raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Fonseca'),
      ReferenceVin(nom: 'Dow\'s', alias: ['dows']),
      ReferenceVin(nom: 'Real Companhia Velha', alias: ['velhotes'],
          raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Sandeman', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'pt_douro',
    pays: 'Portugal',
    nom: 'Douro (vins secs)',
    elevages: {'red': Elevage(ContenantElevage.barrique, 15)},
    alias: ['douro', 'cima corgo', 'douro superior'],
    cepages: ['Touriga Nacional', 'Touriga Franca'],
    longevites: {
      'red': AgingProfile(id: 'douro_rouge', libelle: 'Douro rouge',
          debut: 3, picDebut: 7, picFin: 16, fin: 22),
      'white': AgingProfile(id: 'douro_blanc', libelle: 'Douro blanc',
          debut: 1, picDebut: 2, picFin: 7, fin: 11),
    },
    references: [
      ReferenceVin(nom: 'Barca Velha',
          longevite: AgingProfile(id: 'barca_velha', libelle: 'Barca Velha',
              debut: 8, picDebut: 15, picFin: 35, fin: 50)),
      ReferenceVin(nom: 'Quinta do Crasto'),
      ReferenceVin(nom: 'Niepoort'),
    ],
  ),
  RegionVin(
    id: 'pt_vinho_verde',
    pays: 'Portugal',
    nom: 'Vinho Verde',
    elevages: {'white': Elevage(ContenantElevage.inox, 3)},
    alias: ['vinho verde', 'alvarinho', 'melgaco', 'moncao'],
    cepages: ['Alvarinho', 'Loureiro'],
    longevites: {'white': AgingProfile(id: 'vinho_verde', libelle: 'Vinho Verde',
        debut: 0, picDebut: 1, picFin: 4, fin: 7)},
    references: [
      ReferenceVin(nom: 'Soalheiro'),
      ReferenceVin(nom: 'Casal Garcia', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'pt_dao_bairrada',
    pays: 'Portugal',
    nom: 'Dão, Bairrada & Centre',
    alias: ['dao', 'bairrada', 'beiras'],
    cepages: ['Touriga Nacional', 'Baga'],
    longevites: {'red': AgingProfile(id: 'dao', libelle: 'Dão & Bairrada',
        debut: 3, picDebut: 6, picFin: 15, fin: 22)},
    references: [ReferenceVin(nom: 'Luis Pato')],
  ),
  RegionVin(
    id: 'pt_alentejo',
    pays: 'Portugal',
    nom: 'Alentejo & Lisboa',
    alias: ['alentejo', 'lisboa', 'setubal', 'tejo', 'peninsula de setubal'],
    cepages: ['Aragonez', 'Trincadeira', 'Alicante Bouschet'],
    longevites: {
      'red': AgingProfile(id: 'alentejo', libelle: 'Alentejo',
          debut: 2, picDebut: 4, picFin: 11, fin: 16),
      'fortified': AgingProfile(id: 'setubal', libelle: 'Moscatel de Setúbal',
          debut: 1, picDebut: 5, picFin: 25, fin: 40),
    },
    references: [ReferenceVin(nom: 'Esporão', alias: ['esporao'],
        raison: RaisonDePresence.lesDeux)],
  ),
  RegionVin(
    id: 'pt_madere',
    pays: 'Portugal',
    nom: 'Madère',
    elevages: {'*': Elevage(ContenantElevage.foudre, 36, impose: true)},
    alias: ['madeira', 'madere', 'sercial', 'verdelho', 'bual', 'malmsey'],
    cepages: ['Sercial', 'Verdelho', 'Bual', 'Malvasia'],
    longevites: {'*': AgingProfile(id: 'madeira', libelle: 'Madère',
        debut: 2, picDebut: 15, picFin: 60, fin: 100)},
    references: [
      ReferenceVin(nom: 'Blandy\'s', alias: ['blandys'],
          raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Barbeito'),
    ],
  ),
];
