import 'wine_world_model.dart';

/// Italie — le pays où la longévité est la plus mal estimée par défaut : un Barolo et un
/// Prosecco partagent une nationalité et rien d'autre.
const List<RegionVin> regionsItalie = [
  // Barolo : dix-huit mois sous bois au minimum (trente-huit de vieillissement). Le
  // Barbaresco (neuf mois) et le Langhe Nebbiolo (aucun) n'ont pas cette règle : ils
  // étaient rangés ici, avec le bois « imposé » du Barolo (30/09).
  RegionVin(
    id: 'it_barolo',
    pays: 'Italie',
    nom: 'Barolo',
    elevages: {'red': Elevage(ContenantElevage.foudre, 18, impose: true)},
    alias: ['barolo'],
    cepages: ['Nebbiolo'],
    longevites: {'red': AgingProfile(id: 'barolo', libelle: 'Barolo',
        debut: 5, picDebut: 10, picFin: 20, fin: 25)},
    references: [
      ReferenceVin(nom: 'Giacomo Conterno', alias: ['conterno monfortino'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'monfortino', libelle: 'Monfortino',
              debut: 10, picDebut: 20, picFin: 45, fin: 60),
          elevage: Elevage(ContenantElevage.foudre, 84)),
      ReferenceVin(nom: 'Bruno Giacosa'),
      ReferenceVin(nom: 'Gaja', certitude: Certitude.verifiee),
      ReferenceVin(nom: 'Vietti'),
      ReferenceVin(nom: 'Bartolo Mascarello'),
      ReferenceVin(nom: 'Giuseppe Rinaldi'),
      ReferenceVin(nom: 'Pio Cesare'),
      ReferenceVin(nom: 'Fontanafredda', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'it_barbaresco',
    pays: 'Italie',
    nom: 'Barbaresco',
    elevages: {'red': Elevage(ContenantElevage.foudre, 9, impose: true)},
    alias: ['barbaresco'],
    cepages: ['Nebbiolo'],
    longevites: {'red': AgingProfile(id: 'barbaresco', libelle: 'Barbaresco',
        debut: 4, picDebut: 7, picFin: 15, fin: 20)},
  ),
  RegionVin(
    id: 'it_langhe_nebbiolo',
    pays: 'Italie',
    nom: 'Langhe Nebbiolo & Roero',
    alias: ['langhe nebbiolo', 'nebbiolo d\'alba', 'roero'],
    cepages: ['Nebbiolo'],
    longevites: {'red': AgingProfile(id: 'langhe_nebbiolo', libelle: 'Langhe Nebbiolo',
        debut: 1, picDebut: 3, picFin: 7, fin: 10)},
  ),
  RegionVin(
    id: 'it_piemonte_autres',
    pays: 'Italie',
    nom: 'Piémont — Barbera, Dolcetto, Gavi',
    elevages: {'red': Elevage(ContenantElevage.inox, 8)},
    alias: ['barbera', 'dolcetto', 'gavi', 'alba', 'asti', 'moscato d\'asti',
      'gattinara', 'ghemme'],
    cepages: ['Barbera', 'Dolcetto', 'Cortese'],
    longevites: {
      'red': AgingProfile(id: 'piemonte_rouge', libelle: 'Piémont rouge',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
      'white': AgingProfile(id: 'gavi', libelle: 'Gavi',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
    },
  ),
  // Le Rosso di Montalcino avant le Brunello : il n'a aucune durée de bois imposée, et
  // héritait des vingt-quatre mois du Brunello (30/09).
  RegionVin(
    id: 'it_rosso_montalcino',
    pays: 'Italie',
    nom: 'Rosso di Montalcino',
    alias: ['rosso di montalcino'],
    cepages: ['Sangiovese'],
    longevites: {'red': AgingProfile(id: 'rosso_montalcino', libelle: 'Rosso di Montalcino',
        debut: 1, picDebut: 2, picFin: 6, fin: 9)},
  ),
  RegionVin(
    id: 'it_brunello',
    pays: 'Italie',
    nom: 'Brunello di Montalcino',
    elevages: {'red': Elevage(ContenantElevage.foudre, 24, impose: true)},
    alias: ['brunello', 'montalcino'],
    cepages: ['Sangiovese'],
    longevites: {'red': AgingProfile(id: 'brunello', libelle: 'Brunello',
        debut: 5, picDebut: 9, picFin: 18, fin: 25)},
    references: [
      ReferenceVin(nom: 'Biondi-Santi', alias: ['biondi santi'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'biondi_santi', libelle: 'Biondi-Santi',
              debut: 10, picDebut: 20, picFin: 45, fin: 60),
          elevage: Elevage(ContenantElevage.foudre, 36)),
      ReferenceVin(nom: 'Soldera'),
      ReferenceVin(nom: 'Casanova di Neri'),
      ReferenceVin(nom: 'Banfi', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_chianti',
    pays: 'Italie',
    nom: 'Chianti & Toscane centrale',
    elevages: {'red': Elevage(ContenantElevage.foudre, 12)},
    alias: ['chianti', 'chianti classico', 'vino nobile', 'montepulciano',
      'carmignano', 'morellino'],
    cepages: ['Sangiovese'],
    // Le Chianti sans mention ; Riserva et Gran Selezione passent par le rang.
    longevites: {'red': AgingProfile(id: 'chianti', libelle: 'Chianti',
        debut: 1, picDebut: 3, picFin: 7, fin: 9)},
    references: [
      ReferenceVin(nom: 'Castello di Ama'),
      ReferenceVin(nom: 'Fontodi'),
      ReferenceVin(nom: 'Isole e Olena'),
      ReferenceVin(nom: 'Antinori', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Ruffino', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_bolgheri',
    pays: 'Italie',
    nom: 'Bolgheri & Maremme',
    elevages: {'red': Elevage(ContenantElevage.barrique, 18)},
    alias: ['bolgheri', 'maremma', 'sassicaia', 'toscana igt'],
    cepages: ['Cabernet Sauvignon', 'Merlot', 'Cabernet Franc'],
    longevites: {'red': AgingProfile(id: 'bolgheri', libelle: 'Bolgheri',
        debut: 2, picDebut: 4, picFin: 9, fin: 12)},
    references: [
      ReferenceVin(nom: 'Sassicaia', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'sassicaia', libelle: 'Sassicaia',
              debut: 6, picDebut: 12, picFin: 30, fin: 45),
          elevage: Elevage(ContenantElevage.barrique, 24)),
      ReferenceVin(nom: 'Ornellaia'),
      ReferenceVin(nom: 'Masseto',
          longevite: AgingProfile(id: 'masseto', libelle: 'Masseto',
              debut: 6, picDebut: 12, picFin: 30, fin: 38)),
      ReferenceVin(nom: 'Tignanello'),
    ],
  ),
  // L'Amarone à part : deux ans de vieillissement au minimum (sans que le bois soit
  // exigé). Valpolicella, Ripasso et Bardolino se boivent jeunes, et recevaient la garde
  // et le bois « imposé » de l'Amarone (30/09).
  RegionVin(
    id: 'it_amarone',
    pays: 'Italie',
    nom: 'Amarone & Recioto',
    elevages: {'red': Elevage(ContenantElevage.foudre, 24)},
    alias: ['amarone', 'recioto'],
    cepages: ['Corvina', 'Rondinella'],
    longevites: {'red': AgingProfile(id: 'amarone', libelle: 'Amarone',
        debut: 4, picDebut: 6, picFin: 14, fin: 20)},
    references: [
      ReferenceVin(nom: 'Giuseppe Quintarelli', alias: ['quintarelli'],
          elevage: Elevage(ContenantElevage.foudre, 84)),
      ReferenceVin(nom: 'Dal Forno Romano', alias: ['dal forno']),
    ],
  ),
  RegionVin(
    id: 'it_veneto',
    pays: 'Italie',
    nom: 'Vénétie — Valpolicella, Bardolino & Soave',
    elevages: {'white': Elevage(ContenantElevage.inox, 6)},
    alias: ['valpolicella', 'ripasso', 'bardolino', 'soave'],
    cepages: ['Corvina', 'Rondinella', 'Garganega'],
    longevites: {
      'red': AgingProfile(id: 'valpolicella', libelle: 'Valpolicella & Ripasso',
          debut: 1, picDebut: 2, picFin: 5, fin: 7),
      'white': AgingProfile(id: 'soave', libelle: 'Soave',
          debut: 0, picDebut: 1, picFin: 3, fin: 5),
    },
    references: [
      ReferenceVin(nom: 'Masi', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_prosecco',
    pays: 'Italie',
    nom: 'Prosecco & effervescents italiens',
    elevages: {'*': Elevage(ContenantElevage.inox, 3)},
    alias: ['prosecco', 'valdobbiadene', 'conegliano', 'lambrusco',
      'franciacorta'],
    cepages: ['Glera'],
    longevites: {'*': AgingProfile(id: 'prosecco', libelle: 'Prosecco',
        debut: 0, picDebut: 0, picFin: 2, fin: 3)},
    references: [
      ReferenceVin(nom: 'Ca\' del Bosco', alias: ['ca del bosco'],
          longevite: AgingProfile(id: 'franciacorta', libelle: 'Franciacorta',
              debut: 1, picDebut: 3, picFin: 10, fin: 15)),
      ReferenceVin(nom: 'Bellavista'),
      ReferenceVin(nom: 'La Marca', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_aglianico',
    pays: 'Italie',
    nom: 'Campanie & Basilicate',
    elevages: {'red': Elevage(ContenantElevage.foudre, 18)},
    alias: ['aglianico', 'taurasi', 'vulture', 'greco di tufo',
      'fiano di avellino', 'falanghina'],
    cepages: ['Aglianico', 'Fiano', 'Greco'],
    longevites: {
      'red': AgingProfile(id: 'aglianico', libelle: 'Aglianico',
          debut: 3, picDebut: 5, picFin: 11, fin: 16),
      'white': AgingProfile(id: 'fiano', libelle: 'Fiano & Greco',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
    },
    references: [
      ReferenceVin(nom: 'Mastroberardino'),
      ReferenceVin(nom: 'Cantine del Notaio'),
    ],
  ),
  RegionVin(
    id: 'it_sicile',
    pays: 'Italie',
    nom: 'Sicile & Etna',
    elevages: {'red': Elevage(ContenantElevage.foudre, 12)},
    alias: ['etna', 'sicilia', 'nero d\'avola', 'cerasuolo di vittoria',
      'marsala'],
    cepages: ['Nerello Mascalese', 'Nero d\'Avola', 'Carricante'],
    longevites: {
      'red': AgingProfile(id: 'etna_rouge', libelle: 'Etna & Sicile rouge',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
      'white': AgingProfile(id: 'etna_blanc', libelle: 'Etna blanc',
          debut: 1, picDebut: 2, picFin: 6, fin: 9),
      'fortified': AgingProfile(id: 'marsala', libelle: 'Marsala',
          debut: 1, picDebut: 5, picFin: 25, fin: 40),
    },
    references: [
      ReferenceVin(nom: 'Passopisciaro'),
      ReferenceVin(nom: 'Planeta', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Donnafugata', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'it_pouilles',
    pays: 'Italie',
    nom: 'Pouilles & Sud',
    alias: ['puglia', 'primitivo', 'salice salentino', 'negroamaro',
      'manduria'],
    cepages: ['Primitivo', 'Negroamaro'],
    longevites: {'red': AgingProfile(id: 'primitivo', libelle: 'Primitivo',
        debut: 1, picDebut: 3, picFin: 8, fin: 12)},
  ),
  RegionVin(
    id: 'it_nord_est',
    pays: 'Italie',
    nom: 'Nord-Est — Frioul, Trentin, Haut-Adige',
    alias: ['friuli', 'collio', 'alto adige', 'trentino', 'sudtirol',
      'pinot grigio'],
    cepages: ['Pinot Grigio', 'Friulano', 'Lagrein'],
    longevites: {
      'white': AgingProfile(id: 'nord_est_blanc', libelle: 'Blanc du Nord-Est',
          debut: 1, picDebut: 2, picFin: 7, fin: 11),
      'red': AgingProfile(id: 'nord_est_rouge', libelle: 'Rouge du Nord-Est',
          debut: 1, picDebut: 3, picFin: 9, fin: 13),
    },
    references: [
      ReferenceVin(nom: 'Jermann'),
      ReferenceVin(nom: 'Santa Margherita', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_abruzzes',
    pays: 'Italie',
    nom: 'Abruzzes & Marches',
    alias: ['montepulciano d\'abruzzo', 'trebbiano d\'abruzzo', 'verdicchio',
      'rosso conero'],
    cepages: ['Montepulciano', 'Verdicchio'],
    longevites: {
      'red': AgingProfile(id: 'abruzzo_rouge', libelle: 'Montepulciano d\'Abruzzo',
          debut: 1, picDebut: 3, picFin: 9, fin: 14),
      'white': AgingProfile(id: 'verdicchio', libelle: 'Verdicchio',
          debut: 1, picDebut: 2, picFin: 7, fin: 11),
    },
    references: [
      ReferenceVin(nom: 'Emidio Pepe',
          longevite: AgingProfile(id: 'emidio_pepe', libelle: 'Emidio Pepe',
              debut: 5, picDebut: 12, picFin: 30, fin: 38)),
      ReferenceVin(nom: 'Valentini'),
    ],
  ),
];
