import 'wine_world_model.dart';

/// France — 45 régions.
///
/// Le pays où l'erreur coûte le plus cher des deux côtés : il concentre les vins de
/// prestige (Bordeaux, Bourgogne, Champagne, Sauternes) et une part énorme du volume
/// scanné (Côtes du Rhône, Languedoc, Provence, Beaujolais).
const List<RegionVin> regionsFrance = [
  // ═══════════════ BORDEAUX ═══════════════
  RegionVin(
    id: 'fr_medoc_crus',
    pays: 'France',
    nom: 'Médoc — communales de prestige',
    elevages: {'red': Elevage(ContenantElevage.barrique, 18)},
    alias: ['margaux', 'pauillac', 'saint-julien', 'saint julien',
      'saint-estephe', 'saint estephe'],
    cepages: ['Cabernet Sauvignon', 'Merlot', 'Cabernet Franc', 'Petit Verdot'],
    // Le vin « standard » de ces communes (non classé, négoce) : dix à vingt ans. Un cru
    // classé passe par le rang « sommet » (× 1,9), soit une quarantaine d'années ; les
    // premiers crus ont leur propre fiche. Jusqu'au 30/09 la base valait 28 ans, et un
    // cru classé en recevait 53.
    longevites: {'red': AgingProfile(id: 'medoc_cru', libelle: 'Médoc communal',
        debut: 4, picDebut: 8, picFin: 14, fin: 20)},
    references: [
      ReferenceVin(nom: 'Château Margaux', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'margaux_1er', libelle: 'Premier cru',
              debut: 10, picDebut: 18, picFin: 40, fin: 60),
          elevage: Elevage(ContenantElevage.barrique, 22)),
      ReferenceVin(nom: 'Château Latour', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'latour_1er', libelle: 'Premier cru',
              debut: 12, picDebut: 20, picFin: 45, fin: 70),
          elevage: Elevage(ContenantElevage.barrique, 20)),
      ReferenceVin(nom: 'Château Lafite Rothschild', alias: ['lafite'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'lafite_1er', libelle: 'Premier cru',
              debut: 10, picDebut: 20, picFin: 45, fin: 65),
          elevage: Elevage(ContenantElevage.barrique, 20)),
      ReferenceVin(nom: 'Château Mouton Rothschild', alias: ['mouton'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'mouton_1er', libelle: 'Premier cru',
              debut: 10, picDebut: 18, picFin: 40, fin: 60),
          elevage: Elevage(ContenantElevage.barrique, 20)),
      ReferenceVin(nom: 'Château Pichon Baron', alias: ['pichon-longueville baron']),
      ReferenceVin(nom: 'Château Pichon Comtesse', alias: ['pichon lalande']),
      ReferenceVin(nom: 'Château Léoville-Las Cases', alias: ['leoville las cases']),
      ReferenceVin(nom: 'Château Cos d\'Estournel', alias: ['cos destournel']),
      ReferenceVin(nom: 'Château Montrose'),
      ReferenceVin(nom: 'Château Palmer'),
      ReferenceVin(nom: 'Château Lynch-Bages', alias: ['lynch bages']),
      ReferenceVin(nom: 'Château Ducru-Beaucaillou', alias: ['ducru beaucaillou']),
      ReferenceVin(nom: 'Château Talbot'),
      ReferenceVin(nom: 'Château Gloria'),
      ReferenceVin(nom: 'Château Lynch-Moussas', alias: ['lynch moussas']),
    ],
  ),
  RegionVin(
    id: 'fr_moulis_listrac',
    pays: 'France',
    nom: 'Moulis & Listrac',
    elevages: {'red': Elevage(ContenantElevage.barrique, 14)},
    alias: ['moulis', 'listrac'],
    cepages: ['Cabernet Sauvignon', 'Merlot'],
    longevites: {'red': AgingProfile(id: 'moulis_listrac', libelle: 'Moulis & Listrac',
        debut: 3, picDebut: 6, picFin: 12, fin: 16)},
    references: [ReferenceVin(nom: 'Château Chasse-Spleen', alias: ['chasse spleen'])],
  ),
  RegionVin(
    id: 'fr_medoc_haut',
    pays: 'France',
    nom: 'Haut-Médoc & Médoc',
    alias: ['haut-medoc', 'haut medoc', 'medoc'],
    cepages: ['Cabernet Sauvignon', 'Merlot'],
    longevites: {'red': AgingProfile(id: 'haut_medoc', libelle: 'Haut-Médoc',
        debut: 3, picDebut: 5, picFin: 11, fin: 15)},
    references: [
      ReferenceVin(nom: 'Château Sociando-Mallet', alias: ['sociando mallet']),
      ReferenceVin(nom: 'Château Cantemerle'),
      ReferenceVin(nom: 'Château La Lagune'),
    ],
  ),
  // Les satellites avant Saint-Émilion : « Puisseguin Saint-Émilion » contient
  // « saint-emilion », et en héritait les vingt-quatre ans.
  RegionVin(
    id: 'fr_satellites_libournais',
    pays: 'France',
    nom: 'Satellites du Libournais',
    elevages: {'red': Elevage(ContenantElevage.barrique, 12)},
    alias: ['puisseguin', 'lussac', 'montagne saint-emilion', 'montagne-saint-emilion',
      'saint-georges saint-emilion', 'saint-georges-saint-emilion', 'castillon',
      'francs', 'lalande-de-pomerol', 'lalande de pomerol', 'lalande',
      'fronsac', 'canon-fronsac'],
    cepages: ['Merlot', 'Cabernet Franc'],
    longevites: {'red': AgingProfile(id: 'satellites_libournais', libelle: 'Satellites du Libournais',
        debut: 2, picDebut: 4, picFin: 9, fin: 13)},
    references: [
      ReferenceVin(nom: 'Château Chêne-Vieux', alias: ['chene-vieux', 'chene vieux']),
      ReferenceVin(nom: 'Château de Musset'),
    ],
  ),
  RegionVin(
    id: 'fr_saint_emilion',
    pays: 'France',
    nom: 'Saint-Émilion',
    elevages: {'red': Elevage(ContenantElevage.barrique, 16)},
    alias: ['saint-emilion', 'saint emilion'],
    cepages: ['Merlot', 'Cabernet Franc'],
    // « Saint-Émilion grand cru » est une appellation, pas un classement : le rang le
    // traite en « supérieur » (voir AgingReference.rangDe), le cru classé en « sommet ».
    longevites: {'red': AgingProfile(id: 'saint_emilion', libelle: 'Saint-Émilion',
        debut: 3, picDebut: 6, picFin: 12, fin: 16)},
    references: [
      ReferenceVin(nom: 'Château Cheval Blanc', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'cheval_blanc', libelle: 'Premier grand cru A',
              debut: 10, picDebut: 18, picFin: 40, fin: 60),
          elevage: Elevage(ContenantElevage.barrique, 18)),
      ReferenceVin(nom: 'Château Ausone', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'ausone', libelle: 'Premier grand cru A',
              debut: 10, picDebut: 20, picFin: 40, fin: 60)),
      ReferenceVin(nom: 'Château Angélus', alias: ['angelus']),
      ReferenceVin(nom: 'Château Pavie'),
      ReferenceVin(nom: 'Château Figeac'),
      ReferenceVin(nom: 'Château Canon'),
      ReferenceVin(nom: 'Château Troplong Mondot'),
    ],
  ),
  RegionVin(
    id: 'fr_pomerol',
    pays: 'France',
    nom: 'Pomerol',
    elevages: {'red': Elevage(ContenantElevage.barrique, 18)},
    alias: ['pomerol'],
    cepages: ['Merlot', 'Cabernet Franc'],
    longevites: {'red': AgingProfile(id: 'pomerol', libelle: 'Pomerol',
        debut: 4, picDebut: 7, picFin: 14, fin: 19)},
    references: [
      ReferenceVin(nom: 'Pétrus', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'petrus', libelle: 'Pétrus',
              debut: 10, picDebut: 20, picFin: 45, fin: 65),
          elevage: Elevage(ContenantElevage.barrique, 18)),
      ReferenceVin(nom: 'Château Le Pin', alias: ['le pin']),
      ReferenceVin(nom: 'Château Lafleur'),
      ReferenceVin(nom: 'Château Trotanoy'),
      ReferenceVin(nom: 'Vieux Château Certan', alias: ['vieux chateau certan']),
      ReferenceVin(nom: 'Château L\'Évangile', alias: ['levangile']),
    ],
  ),
  RegionVin(
    id: 'fr_pessac',
    pays: 'France',
    nom: 'Pessac-Léognan',
    elevages: {'red': Elevage(ContenantElevage.barrique, 16),
      'white': Elevage(ContenantElevage.barrique, 10)},
    alias: ['pessac-leognan', 'pessac leognan', 'pessac'],
    cepages: ['Cabernet Sauvignon', 'Merlot', 'Sauvignon Blanc', 'Sémillon'],
    longevites: {
      'red': AgingProfile(id: 'pessac_rouge', libelle: 'Pessac rouge',
          debut: 3, picDebut: 7, picFin: 13, fin: 18),
      'white': AgingProfile(id: 'pessac_blanc', libelle: 'Pessac blanc',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
    },
    references: [
      ReferenceVin(nom: 'Château Haut-Brion', alias: ['haut brion'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'haut_brion', libelle: 'Premier cru',
              debut: 10, picDebut: 18, picFin: 40, fin: 60),
          elevage: Elevage(ContenantElevage.barrique, 22)),
      ReferenceVin(nom: 'Château La Mission Haut-Brion'),
      ReferenceVin(nom: 'Domaine de Chevalier'),
      ReferenceVin(nom: 'Château Smith Haut Lafitte'),
      ReferenceVin(nom: 'Château Carbonnieux'),
    ],
  ),
  RegionVin(
    id: 'fr_graves',
    pays: 'France',
    nom: 'Graves',
    elevages: {'red': Elevage(ContenantElevage.barrique, 12),
      'white': Elevage(ContenantElevage.inox, 6)},
    alias: ['graves'],
    cepages: ['Merlot', 'Cabernet Sauvignon', 'Sauvignon Blanc', 'Sémillon'],
    longevites: {
      'red': AgingProfile(id: 'graves_rouge', libelle: 'Graves rouge',
          debut: 2, picDebut: 4, picFin: 9, fin: 13),
      'white': AgingProfile(id: 'graves_blanc', libelle: 'Graves blanc',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
      'sweet': AgingProfile(id: 'graves_superieures', libelle: 'Graves supérieures',
          debut: 2, picDebut: 5, picFin: 12, fin: 18),
    },
    references: [ReferenceVin(nom: 'Château Crabitey')],
  ),
  RegionVin(
    id: 'fr_bordeaux_generique',
    pays: 'France',
    nom: 'Bordeaux & Bordeaux Supérieur',
    elevages: {'red': Elevage(ContenantElevage.inox, 6),
      'white': Elevage(ContenantElevage.inox, 4)},
    alias: ['bordeaux superieur', 'bordeaux', 'entre-deux-mers',
      'cotes de bourg', 'blaye'],
    cepages: ['Merlot', 'Cabernet Sauvignon', 'Sauvignon Blanc'],
    longevites: {
      // Un Bordeaux ou Bordeaux supérieur se boit dans ses cinq à dix ans ; la base en
      // donnait quinze, et la tolérance de 1,8 laissait passer vingt-sept.
      'red': AgingProfile(id: 'bdx_generique_rouge', libelle: 'Bordeaux',
          debut: 1, picDebut: 2, picFin: 6, fin: 9),
      'white': AgingProfile(id: 'bdx_generique_blanc', libelle: 'Bordeaux blanc',
          debut: 0, picDebut: 1, picFin: 3, fin: 5),
      'rose': AgingProfile(id: 'bdx_rose', libelle: 'Bordeaux rosé',
          debut: 0, picDebut: 1, picFin: 2, fin: 3),
    },
    references: [
      ReferenceVin(nom: 'Mouton Cadet', raison: RaisonDePresence.grandVolume,
          longevite: AgingProfile(id: 'mouton_cadet', libelle: 'Mouton Cadet',
              debut: 1, picDebut: 2, picFin: 5, fin: 8)),
      ReferenceVin(nom: 'Michel Lynch', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'fr_sauternes',
    pays: 'France',
    nom: 'Sauternes & Barsac',
    elevages: {'*': Elevage(ContenantElevage.barrique, 18)},
    alias: ['sauternes', 'barsac'],
    cepages: ['Sémillon', 'Sauvignon Blanc', 'Muscadelle'],
    longevites: {'*': AgingProfile(id: 'sauternes', libelle: 'Sauternes',
        debut: 3, picDebut: 8, picFin: 22, fin: 35)},
    references: [
      ReferenceVin(nom: 'Château d\'Yquem', alias: ['yquem'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'yquem', libelle: 'Yquem',
              debut: 5, picDebut: 15, picFin: 60, fin: 100),
          elevage: Elevage(ContenantElevage.barrique, 36)),
      ReferenceVin(nom: 'Château Climens'),
      ReferenceVin(nom: 'Château Suduiraut'),
      ReferenceVin(nom: 'Château Rieussec'),
      ReferenceVin(nom: 'Château Coutet'),
      ReferenceVin(nom: 'Château Bastor-Lamontagne'),
      // « So Sauternes » : une cuvée pensée pour être bue jeune, sur le fruit (l'IA lui
      // donnait cinquante ans de garde, 30/09).
      ReferenceVin(nom: 'So Sauternes', raison: RaisonDePresence.grandVolume,
          longevite: AgingProfile(id: 'so_sauternes', libelle: 'So Sauternes',
              debut: 0, picDebut: 1, picFin: 5, fin: 9)),
    ],
  ),
  RegionVin(
    id: 'fr_liquoreux_voisins',
    pays: 'France',
    nom: 'Liquoreux voisins de Sauternes',
    elevages: {'*': Elevage(ContenantElevage.barrique, 12)},
    alias: ['cerons', 'loupiac', 'sainte-croix-du-mont', 'cadillac', 'monbazillac', 'saussignac'],
    cepages: ['Sémillon', 'Sauvignon Blanc', 'Muscadelle'],
    longevites: {'*': AgingProfile(id: 'liquoreux_voisins', libelle: 'Liquoreux de la Garonne et de Bergerac',
        debut: 2, picDebut: 5, picFin: 12, fin: 18)},
  ),

  // ═══════════════ BOURGOGNE ═══════════════
  RegionVin(
    id: 'fr_cote_de_nuits',
    pays: 'France',
    nom: 'Côte de Nuits',
    elevages: {'red': Elevage(ContenantElevage.barrique, 16)},
    alias: ['gevrey-chambertin', 'gevrey', 'chambolle-musigny', 'chambolle',
      'vosne-romanee', 'vosne', 'morey-saint-denis',
      'nuits-saint-georges', 'morey-saint-denis', 'vougeot', 'fixin',
      'marsannay', 'cote de nuits'],
    cepages: ['Pinot Noir'],
    // Le village. Un premier ou un grand cru passe par le rang « sommet » (× 1,9).
    longevites: {
      'red': AgingProfile(id: 'cdn_rouge', libelle: 'Côte de Nuits',
          debut: 3, picDebut: 5, picFin: 11, fin: 15),
      'white': AgingProfile(id: 'cdn_blanc', libelle: 'Côte de Nuits blanc',
          debut: 2, picDebut: 3, picFin: 7, fin: 10),
    },
    references: [
      ReferenceVin(nom: 'Domaine de la Romanée-Conti', alias: ['romanee-conti', 'drc'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'drc', libelle: 'DRC',
              debut: 10, picDebut: 20, picFin: 45, fin: 65),
          elevage: Elevage(ContenantElevage.barrique, 18)),
      ReferenceVin(nom: 'Domaine Leroy'),
      ReferenceVin(nom: 'Domaine Armand Rousseau', alias: ['armand rousseau']),
      ReferenceVin(nom: 'Domaine Dujac'),
      ReferenceVin(nom: 'Domaine Georges Roumier', alias: ['roumier']),
      ReferenceVin(nom: 'Domaine Méo-Camuzet', alias: ['meo camuzet']),
      ReferenceVin(nom: 'Domaine Ponsot'),
      ReferenceVin(nom: 'Faiveley'),
      ReferenceVin(nom: 'Joseph Drouhin', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Louis Jadot', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'fr_cote_de_beaune',
    pays: 'France',
    nom: 'Côte de Beaune',
    elevages: {'red': Elevage(ContenantElevage.barrique, 14),
      'white': Elevage(ContenantElevage.barrique, 12)},
    alias: ['pommard', 'volnay', 'beaune', 'meursault', 'puligny-montrachet',
      'chassagne-montrachet', 'corton', 'aloxe-corton', 'savigny',
      'saint-aubin', 'santenay', 'cote de beaune', 'montrachet'],
    cepages: ['Pinot Noir', 'Chardonnay'],
    // Le village (Chorey, Savigny, Santenay, Meursault village…). Un premier ou un grand
    // cru passe par le rang « sommet » (× 1,9).
    longevites: {
      'red': AgingProfile(id: 'cdb_rouge', libelle: 'Côte de Beaune rouge',
          debut: 2, picDebut: 4, picFin: 9, fin: 12),
      'white': AgingProfile(id: 'cdb_blanc', libelle: 'Côte de Beaune blanc',
          debut: 2, picDebut: 3, picFin: 8, fin: 11),
    },
    references: [
      ReferenceVin(nom: 'Domaine Leflaive'),
      ReferenceVin(nom: 'Domaine Coche-Dury', alias: ['coche dury'],
          elevage: Elevage(ContenantElevage.barrique, 20)),
      ReferenceVin(nom: 'Domaine des Comtes Lafon', alias: ['comtes lafon'],
          elevage: Elevage(ContenantElevage.barrique, 18)),
      ReferenceVin(nom: 'Domaine Ramonet'),
      ReferenceVin(nom: 'Bouchard Père & Fils', alias: ['bouchard pere']),
      ReferenceVin(nom: 'Olivier Leflaive'),
    ],
  ),
  RegionVin(
    id: 'fr_chablis',
    pays: 'France',
    nom: 'Chablis',
    elevages: {'white': Elevage(ContenantElevage.inox, 8)},
    alias: ['chablis', 'petit chablis', 'irancy'],
    cepages: ['Chardonnay'],
    longevites: {'white': AgingProfile(id: 'chablis', libelle: 'Chablis',
        debut: 1, picDebut: 2, picFin: 6, fin: 9)},
    references: [
      ReferenceVin(nom: 'Domaine Raveneau', alias: ['raveneau']),
      ReferenceVin(nom: 'Domaine Dauvissat', alias: ['vincent dauvissat']),
      ReferenceVin(nom: 'William Fèvre', alias: ['william fevre']),
      ReferenceVin(nom: 'Domaine Laroche', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'fr_bourgogne_regional',
    pays: 'France',
    nom: 'Bourgogne régional',
    elevages: {'*': Elevage(ContenantElevage.inox, 8)},
    alias: ['bourgogne hautes cotes', 'hautes cotes', 'coteaux bourguignons',
      'bourgogne aligote', 'aligote', 'passetoutgrain', 'bourgogne'],
    cepages: ['Pinot Noir', 'Chardonnay', 'Aligoté', 'Gamay'],
    longevites: {
      'red': AgingProfile(id: 'bgn_reg_rouge', libelle: 'Bourgogne régional',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
      'white': AgingProfile(id: 'bgn_reg_blanc', libelle: 'Bourgogne blanc régional',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
    },
    references: [ReferenceVin(nom: 'Moillard', raison: RaisonDePresence.grandVolume)],
  ),
  RegionVin(
    id: 'fr_cote_chalonnaise',
    pays: 'France',
    nom: 'Côte Chalonnaise & Mâconnais',
    alias: ['mercurey', 'givry', 'rully', 'montagny', 'macon',
      'pouilly-fuisse', 'saint-veran', 'viré-clessé'],
    cepages: ['Pinot Noir', 'Chardonnay'],
    longevites: {
      'red': AgingProfile(id: 'chalon_rouge', libelle: 'Chalonnaise rouge',
          debut: 2, picDebut: 4, picFin: 9, fin: 13),
      'white': AgingProfile(id: 'chalon_blanc', libelle: 'Mâconnais blanc',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
    },
  ),

  // ═══════════════ BEAUJOLAIS ═══════════════
  RegionVin(
    id: 'fr_beaujolais_crus',
    pays: 'France',
    nom: 'Crus du Beaujolais',
    elevages: {'red': Elevage(ContenantElevage.foudre, 9)},
    alias: ['moulin-a-vent', 'morgon', 'fleurie', 'julienas', 'chenas',
      'chiroubles', 'saint-amour', 'regnie', 'brouilly', 'cote de brouilly'],
    cepages: ['Gamay'],
    longevites: {'red': AgingProfile(id: 'beaujolais_cru', libelle: 'Cru du Beaujolais',
        debut: 1, picDebut: 3, picFin: 7, fin: 10)},
    references: [
      ReferenceVin(nom: 'Marcel Lapierre', alias: ['lapierre']),
      ReferenceVin(nom: 'Jean Foillard', alias: ['foillard']),
      ReferenceVin(nom: 'Château des Jacques'),
      ReferenceVin(nom: 'Georges Duboeuf', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'fr_beaujolais_villages',
    pays: 'France',
    nom: 'Beaujolais & Villages',
    elevages: {'red': Elevage(ContenantElevage.inox, 4)},
    alias: ['beaujolais-villages', 'beaujolais nouveau', 'beaujolais',
      'lantignie'],
    cepages: ['Gamay'],
    longevites: {'red': AgingProfile(id: 'beaujolais', libelle: 'Beaujolais',
        debut: 0, picDebut: 1, picFin: 4, fin: 6)},
  ),

  // ═══════════════ RHÔNE ═══════════════
  // Crozes-Hermitage et Saint-Joseph avant l'Hermitage : « crozes-hermitage » contient
  // « hermitage », et en héritait les vingt-cinq ans (Cave de Tain, 30/09). Condrieu et
  // Saint-Péray, blancs à boire jeunes, les rejoignent.
  RegionVin(
    id: 'fr_rhone_nord_village',
    pays: 'France',
    nom: 'Crozes-Hermitage, Saint-Joseph & Condrieu',
    elevages: {'red': Elevage(ContenantElevage.foudre, 12)},
    alias: ['crozes-hermitage', 'crozes', 'saint-joseph', 'condrieu', 'saint-peray',
      // La région seule, sans appellation : le vin le plus courant du nord.
      'rhone septentrional', 'rhone nord', 'northern rhone'],
    cepages: ['Syrah', 'Viognier', 'Marsanne', 'Roussanne'],
    longevites: {
      'red': AgingProfile(id: 'rhone_nord_village_rouge', libelle: 'Crozes & Saint-Joseph',
          debut: 1, picDebut: 3, picFin: 7, fin: 10),
      'white': AgingProfile(id: 'rhone_nord_village_blanc', libelle: 'Condrieu & blancs du nord',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
    },
    references: [
      ReferenceVin(nom: 'Cave de Tain', raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Domaine Alain Graillot', alias: ['graillot']),
    ],
  ),
  RegionVin(
    id: 'fr_rhone_nord',
    pays: 'France',
    nom: 'Rhône septentrional',
    elevages: {'red': Elevage(ContenantElevage.foudre, 18)},
    alias: ['cote-rotie', 'hermitage', 'cornas', 'chateau-grillet'],
    cepages: ['Syrah', 'Viognier', 'Marsanne', 'Roussanne'],
    longevites: {
      'red': AgingProfile(id: 'rhone_nord_rouge', libelle: 'Hermitage, Côte-Rôtie & Cornas',
          debut: 4, picDebut: 8, picFin: 16, fin: 22),
      'white': AgingProfile(id: 'rhone_nord_blanc', libelle: 'Rhône nord blanc',
          debut: 2, picDebut: 4, picFin: 10, fin: 15),
    },
    references: [
      ReferenceVin(nom: 'E. Guigal', alias: ['guigal'], raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Jean-Louis Chave', certitude: Certitude.verifiee, alias: ['chave'],
          longevite: AgingProfile(id: 'chave', libelle: 'Chave Hermitage',
              debut: 8, picDebut: 15, picFin: 35, fin: 50),
          elevage: Elevage(ContenantElevage.foudre, 18)),
      ReferenceVin(nom: 'Domaine Jamet'),
      ReferenceVin(nom: 'Auguste Clape', alias: ['clape']),
      ReferenceVin(nom: 'M. Chapoutier', alias: ['chapoutier'],
          raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Paul Jaboulet Aîné', alias: ['jaboulet']),
    ],
  ),
  RegionVin(
    id: 'fr_chateauneuf',
    pays: 'France',
    nom: 'Châteauneuf-du-Pape',
    elevages: {'red': Elevage(ContenantElevage.foudre, 15)},
    alias: ['chateauneuf-du-pape', 'chateauneuf'],
    cepages: ['Grenache', 'Syrah', 'Mourvèdre'],
    longevites: {'red': AgingProfile(id: 'cnp', libelle: 'Châteauneuf-du-Pape',
        debut: 3, picDebut: 6, picFin: 13, fin: 18)},
    references: [
      ReferenceVin(nom: 'Château Rayas', alias: ['rayas'],
          longevite: AgingProfile(id: 'rayas', libelle: 'Rayas',
              debut: 8, picDebut: 15, picFin: 35, fin: 38),
          elevage: Elevage(ContenantElevage.foudre, 24)),
      ReferenceVin(nom: 'Château de Beaucastel', alias: ['beaucastel']),
      ReferenceVin(nom: 'Domaine du Vieux Télégraphe', alias: ['vieux telegraphe']),
      ReferenceVin(nom: 'Clos des Papes'),
    ],
  ),
  RegionVin(
    id: 'fr_gigondas',
    pays: 'France',
    nom: 'Gigondas & Vacqueyras',
    elevages: {'red': Elevage(ContenantElevage.foudre, 12)},
    alias: ['gigondas', 'vacqueyras'],
    cepages: ['Grenache', 'Syrah', 'Mourvèdre'],
    longevites: {'red': AgingProfile(id: 'gigondas', libelle: 'Gigondas & Vacqueyras',
        debut: 2, picDebut: 4, picFin: 9, fin: 13)},
  ),
  // Cairanne était rangé avec Châteauneuf : un Cairanne de coopérative recevait trente
  // ans (vingt-deux, × 1,35 pour « Réserve »), 30/09.
  RegionVin(
    id: 'fr_crus_rhone_sud',
    pays: 'France',
    nom: 'Crus du Rhône méridional',
    elevages: {'red': Elevage(ContenantElevage.inox, 8)},
    alias: ['cairanne', 'rasteau', 'lirac', 'vinsobres', 'beaumes-de-venise',
      'beaumes de venise', 'cotes du rhone villages'],
    cepages: ['Grenache', 'Syrah', 'Mourvèdre'],
    longevites: {
      'red': AgingProfile(id: 'crus_rhone_sud', libelle: 'Crus du Rhône méridional',
          debut: 1, picDebut: 3, picFin: 7, fin: 10),
      'white': AgingProfile(id: 'crus_rhone_sud_blanc', libelle: 'Blancs du Rhône méridional',
          debut: 0, picDebut: 1, picFin: 3, fin: 5),
    },
  ),
  RegionVin(
    id: 'fr_rhone_villages',
    pays: 'France',
    nom: 'Côtes du Rhône & villages',
    elevages: {'*': Elevage(ContenantElevage.inox, 6)},
    alias: ['cotes du rhone', 'ventoux', 'luberon', 'costieres de nimes',
      'duche d\'uzes', 'uzes', 'grignan', 'vivarais',
      // La région seule, sans appellation : « Vallée du Rhône » ne correspondait à rien,
      // et un vin ainsi décrit n'avait que l'enveloppe de sa couleur (30/09). Le vin le
      // plus courant de la vallée est un côtes-du-rhône. Déclarées ici, après les crus :
      // une appellation reconnue passe toujours avant.
      'vallee du rhone', 'rhone valley', 'valle del rodano', 'rhone meridional',
      'rhone sud', 'southern rhone'],
    cepages: ['Grenache', 'Syrah', 'Carignan'],
    longevites: {
      'red': AgingProfile(id: 'cdr', libelle: 'Côtes du Rhône',
          debut: 1, picDebut: 2, picFin: 5, fin: 7),
      'white': AgingProfile(id: 'cdr_blanc', libelle: 'Côtes du Rhône blanc',
          debut: 0, picDebut: 1, picFin: 3, fin: 4),
      'rose': AgingProfile(id: 'cdr_rose', libelle: 'Rosé du Rhône',
          debut: 0, picDebut: 1, picFin: 2, fin: 3),
    },
  ),
  RegionVin(
    id: 'fr_tavel',
    pays: 'France',
    nom: 'Tavel',
    alias: ['tavel'],
    cepages: ['Grenache', 'Cinsault'],
    longevites: {'*': AgingProfile(id: 'tavel', libelle: 'Tavel',
        debut: 0, picDebut: 1, picFin: 4, fin: 6)},
  ),

  // ═══════════════ PROVENCE & CORSE ═══════════════
  RegionVin(
    id: 'fr_bandol',
    pays: 'France',
    nom: 'Bandol',
    elevages: {'red': Elevage(ContenantElevage.foudre, 18, impose: true),
      'rose': Elevage(ContenantElevage.inox, 6),
      'white': Elevage(ContenantElevage.inox, 8)},
    alias: ['bandol'],
    cepages: ['Mourvèdre', 'Grenache', 'Cinsault'],
    longevites: {
      'red': AgingProfile(id: 'bandol_rouge', libelle: 'Bandol rouge',
          debut: 3, picDebut: 6, picFin: 14, fin: 20),
      // Un rosé de Bandol se boit dans ses trois à cinq ans ; les plus grands tiennent
      // davantage, par leur fiche de domaine. La base en donnait quatorze, et des rosés
      // 2023 s'affichaient « à boire jusqu'en 2037 » (30/09).
      'rose': AgingProfile(id: 'bandol_rose', libelle: 'Bandol rosé',
          debut: 0, picDebut: 1, picFin: 3, fin: 5),
      'white': AgingProfile(id: 'bandol_blanc', libelle: 'Bandol blanc',
          debut: 0, picDebut: 1, picFin: 4, fin: 7),
    },
    references: [
      ReferenceVin(nom: 'Domaine Tempier', alias: ['tempier'],
          certitude: Certitude.verifiee),
      // La longévité de Terrebrune est celle de son rouge ; son rosé, réputé de garde,
      // tient une dizaine d'années.
      ReferenceVin(nom: 'Domaine de Terrebrune', alias: ['terrebrune'],
          certitude: Certitude.verifiee,
          couleurs: {'red'},
          longevite: AgingProfile(id: 'terrebrune', libelle: 'Terrebrune',
              debut: 2, picDebut: 5, picFin: 14, fin: 20),
          longevitesParCouleur: {
            'rose': AgingProfile(id: 'terrebrune_rose', libelle: 'Terrebrune rosé',
                debut: 0, picDebut: 2, picFin: 6, fin: 10),
          }),
      ReferenceVin(nom: 'Château Pradeaux', alias: ['pradeaux']),
      ReferenceVin(nom: 'Château de Pibarnon', alias: ['pibarnon']),
      ReferenceVin(nom: 'Domaine de La Tour du Bon', alias: ['tour du bon'],
          certitude: Certitude.verifiee,
          elevage: Elevage(ContenantElevage.foudre, 20)),
      // « En Sol » : 100 % mourvèdre élevé en TINAJAS — des amphores de terre cuite
      // commandées dans les Dolomites. Aucune règle de région ne peut le deviner, et le
      // vin n'est même pas en AOC Bandol mais en IGP Méditerranée, l'appellation exigeant
      // un assemblage. C'est exactement le cas qui justifie le niveau « domaine ».
      ReferenceVin(nom: 'En Sol', alias: ['tour du bon en sol'],
          certitude: Certitude.verifiee,
          couleurs: {'red'},
          elevage: Elevage(ContenantElevage.amphore, 6),
          longevite: AgingProfile(id: 'en_sol', libelle: 'En Sol',
              debut: 1, picDebut: 3, picFin: 10, fin: 15)),
    ],
  ),
  RegionVin(
    id: 'fr_provence',
    pays: 'France',
    nom: 'Provence',
    elevages: {'rose': Elevage(ContenantElevage.inox, 4),
      'red': Elevage(ContenantElevage.foudre, 12)},
    alias: ['cotes de provence', 'coteaux d\'aix', 'coteaux varois',
      'les baux de provence', 'cassis', 'palette', 'bellet'],
    cepages: ['Grenache', 'Cinsault', 'Syrah', 'Rolle'],
    longevites: {
      'rose': AgingProfile(id: 'provence_rose', libelle: 'Rosé de Provence',
          debut: 0, picDebut: 1, picFin: 2, fin: 4),
      'red': AgingProfile(id: 'provence_rouge', libelle: 'Provence rouge',
          debut: 1, picDebut: 3, picFin: 7, fin: 10),
      'white': AgingProfile(id: 'provence_blanc', libelle: 'Provence blanc',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
    },
    references: [
      ReferenceVin(nom: 'Domaines Ott', alias: ['ott'], raison: RaisonDePresence.lesDeux,
          elevage: Elevage(ContenantElevage.inox, 6)),
      ReferenceVin(nom: 'Whispering Angel', raison: RaisonDePresence.grandVolume,
          longevite: AgingProfile(id: 'whispering_angel', libelle: 'Whispering Angel',
              debut: 0, picDebut: 0, picFin: 2, fin: 3)),
      ReferenceVin(nom: 'Miraval', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'fr_corse',
    pays: 'France',
    nom: 'Corse',
    alias: ['patrimonio', 'ajaccio', 'vin de corse', 'figari', 'sartene'],
    cepages: ['Nielluccio', 'Sciaccarello', 'Vermentino'],
    longevites: {
      'red': AgingProfile(id: 'corse_rouge', libelle: 'Corse rouge',
          debut: 2, picDebut: 4, picFin: 10, fin: 14),
      'white': AgingProfile(id: 'corse_blanc', libelle: 'Corse blanc',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
    },
  ),

  // ═══════════════ LANGUEDOC-ROUSSILLON ═══════════════
  RegionVin(
    id: 'fr_languedoc',
    pays: 'France',
    nom: 'Languedoc',
    elevages: {'red': Elevage(ContenantElevage.foudre, 10)},
    alias: ['languedoc', 'corbieres', 'minervois', 'faugeres',
      'saint-chinian', 'pic saint-loup', 'la clape', 'terrasses du larzac',
      'fitou', 'cabardes', 'limoux'],
    cepages: ['Syrah', 'Grenache', 'Mourvèdre', 'Carignan'],
    longevites: {
      'red': AgingProfile(id: 'languedoc_rouge', libelle: 'Languedoc rouge',
          debut: 1, picDebut: 3, picFin: 7, fin: 10),
      'rose': AgingProfile(id: 'languedoc_rose', libelle: 'Languedoc rosé',
          debut: 0, picDebut: 1, picFin: 2, fin: 3),
      'white': AgingProfile(id: 'languedoc_blanc', libelle: 'Languedoc blanc',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
    },
    references: [
      ReferenceVin(nom: 'Mas de Daumas Gassac', alias: ['daumas gassac'],
          couleurs: {'red'},
          longevite: AgingProfile(id: 'daumas_gassac', libelle: 'Daumas Gassac',
              debut: 4, picDebut: 8, picFin: 20, fin: 28)),
      ReferenceVin(nom: 'Château de Pech-Redon'),
      ReferenceVin(nom: 'Mas Jullien'),
    ],
  ),
  RegionVin(
    id: 'fr_roussillon',
    pays: 'France',
    nom: 'Roussillon',
    alias: ['cotes du roussillon', 'collioure', 'maury sec', 'agly'],
    cepages: ['Grenache', 'Carignan', 'Syrah'],
    longevites: {'red': AgingProfile(id: 'roussillon', libelle: 'Roussillon',
        debut: 1, picDebut: 3, picFin: 8, fin: 12)},
    references: [ReferenceVin(nom: 'Domaine Gauby', alias: ['gauby'])],
  ),
  RegionVin(
    id: 'fr_vdn',
    pays: 'France',
    nom: 'Vins doux naturels',
    elevages: {'*': Elevage(ContenantElevage.foudre, 30)},
    alias: ['banyuls', 'maury', 'rivesaltes', 'muscat de rivesaltes',
      'muscat de beaumes', 'rasteau vdn'],
    cepages: ['Grenache', 'Muscat'],
    longevites: {'*': AgingProfile(id: 'vdn', libelle: 'Vin doux naturel',
        debut: 1, picDebut: 5, picFin: 25, fin: 40)},
  ),

  // ═══════════════ LOIRE ═══════════════
  RegionVin(
    id: 'fr_loire_sauvignon',
    pays: 'France',
    nom: 'Centre-Loire',
    elevages: {'white': Elevage(ContenantElevage.inox, 6)},
    alias: ['sancerre', 'pouilly-fume', 'menetou-salon', 'quincy',
      'reuilly', 'coteaux du giennois'],
    cepages: ['Sauvignon Blanc', 'Pinot Noir'],
    longevites: {
      'white': AgingProfile(id: 'centre_loire_blanc', libelle: 'Sancerre & Pouilly',
          debut: 0, picDebut: 1, picFin: 4, fin: 7),
      'red': AgingProfile(id: 'centre_loire_rouge', libelle: 'Sancerre rouge',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
    },
    references: [
      ReferenceVin(nom: 'Didier Dagueneau', alias: ['dagueneau'],
          longevite: AgingProfile(id: 'dagueneau', libelle: 'Dagueneau',
              debut: 2, picDebut: 5, picFin: 15, fin: 22)),
      ReferenceVin(nom: 'Domaine Vacheron'),
      ReferenceVin(nom: 'Alphonse Mellot'),
    ],
  ),
  RegionVin(
    id: 'fr_loire_chenin',
    pays: 'France',
    nom: 'Chenin de Loire',
    elevages: {'white': Elevage(ContenantElevage.barrique, 10)},
    alias: ['vouvray', 'montlouis', 'savennieres', 'saumur blanc',
      'anjou blanc', 'jasnieres'],
    cepages: ['Chenin Blanc'],
    longevites: {
      'white': AgingProfile(id: 'chenin_sec', libelle: 'Chenin sec',
          debut: 2, picDebut: 5, picFin: 15, fin: 22),
      'sweet': AgingProfile(id: 'chenin_moelleux', libelle: 'Chenin moelleux',
          debut: 3, picDebut: 10, picFin: 30, fin: 45),
    },
    references: [
      ReferenceVin(nom: 'Coulée de Serrant', alias: ['coulee de serrant']),
      ReferenceVin(nom: 'Domaine Huet', alias: ['huet']),
    ],
  ),
  RegionVin(
    id: 'fr_loire_layon',
    pays: 'France',
    nom: 'Coteaux du Layon & liquoreux d\'Anjou',
    alias: ['coteaux du layon', 'quarts de chaume', 'bonnezeaux',
      'chaume'],
    cepages: ['Chenin Blanc'],
    longevites: {'*': AgingProfile(id: 'layon', libelle: 'Layon',
        debut: 3, picDebut: 10, picFin: 30, fin: 45)},
  ),
  RegionVin(
    id: 'fr_loire_rouge',
    pays: 'France',
    nom: 'Cabernet franc de Loire',
    elevages: {'red': Elevage(ContenantElevage.foudre, 10)},
    alias: ['chinon', 'bourgueil', 'saint-nicolas-de-bourgueil',
      'saumur-champigny', 'anjou rouge'],
    cepages: ['Cabernet Franc'],
    longevites: {'red': AgingProfile(id: 'loire_cf', libelle: 'Cabernet franc',
        debut: 1, picDebut: 3, picFin: 8, fin: 12)},
    references: [
      ReferenceVin(nom: 'Charles Joguet'),
      ReferenceVin(nom: 'Clos Rougeard', alias: ['rougeard'],
          couleurs: {'red'},
          longevite: AgingProfile(id: 'rougeard', libelle: 'Clos Rougeard',
              debut: 5, picDebut: 10, picFin: 25, fin: 35),
          elevage: Elevage(ContenantElevage.barrique, 24)),
    ],
  ),
  RegionVin(
    id: 'fr_muscadet',
    pays: 'France',
    nom: 'Muscadet & Nantais',
    elevages: {'white': Elevage(ContenantElevage.beton, 8)},
    alias: ['muscadet', 'sevre et maine', 'gros plant'],
    cepages: ['Melon de Bourgogne'],
    longevites: {'white': AgingProfile(id: 'muscadet', libelle: 'Muscadet',
        debut: 0, picDebut: 1, picFin: 3, fin: 6)},
  ),

  // ═══════════════ ALSACE, JURA, SAVOIE ═══════════════
  RegionVin(
    id: 'fr_alsace',
    pays: 'France',
    nom: 'Alsace',
    elevages: {'white': Elevage(ContenantElevage.foudre, 8)},
    alias: ['alsace', 'alsace grand cru', 'cremant d\'alsace'],
    cepages: ['Riesling', 'Gewurztraminer', 'Pinot Gris', 'Muscat'],
    longevites: {
      // L'Alsace générique ; un grand cru passe par le rang « sommet » (× 1,9).
      'white': AgingProfile(id: 'alsace_blanc', libelle: 'Alsace',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
      'sweet': AgingProfile(id: 'alsace_vt', libelle: 'Vendanges tardives',
          debut: 3, picDebut: 8, picFin: 25, fin: 40),
    },
    references: [
      ReferenceVin(nom: 'Domaine Zind-Humbrecht', alias: ['zind humbrecht']),
      ReferenceVin(nom: 'Domaine Weinbach'),
      ReferenceVin(nom: 'Trimbach', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Hugel', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'fr_jura',
    pays: 'France',
    nom: 'Jura',
    elevages: {'white': Elevage(ContenantElevage.foudre, 30),
      'red': Elevage(ContenantElevage.foudre, 14)},
    alias: ['arbois', 'chateau-chalon', 'cotes du jura', 'l\'etoile',
      'cremant du jura', 'jura'],
    cepages: ['Savagnin', 'Chardonnay', 'Poulsard', 'Trousseau'],
    longevites: {
      // Le blanc ouillé ; le vin jaune passe par le rang « sommet » (voir rangDe).
      'white': AgingProfile(id: 'jura_blanc', libelle: 'Jura blanc',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
      'red': AgingProfile(id: 'jura_rouge', libelle: 'Jura rouge',
          debut: 2, picDebut: 4, picFin: 10, fin: 15),
      'sparkling': AgingProfile(id: 'cremant_jura', libelle: 'Crémant du Jura',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
    },
    references: [
      ReferenceVin(nom: 'Domaine Jean Macle', alias: ['macle'],
          // Le vin jaune est réputé quasi immortel, mais je n'ai pas de source sous la
          // main : la fenêtre reste bien au-dessus de sa catégorie sans affirmer le
          // siècle qu'on lui prête couramment.
          longevite: AgingProfile(id: 'macle', libelle: 'Château-Chalon',
              debut: 5, picDebut: 15, picFin: 30, fin: 38),
          elevage: Elevage(ContenantElevage.foudre, 75, impose: true)),
      ReferenceVin(nom: 'Domaine Ganevat', alias: ['ganevat']),
      ReferenceVin(nom: 'Domaine Tissot', alias: ['stephane tissot']),
    ],
  ),
  RegionVin(
    id: 'fr_savoie',
    pays: 'France',
    nom: 'Savoie & Bugey',
    alias: ['savoie', 'apremont', 'chignin', 'mondeuse', 'bugey', 'seyssel'],
    cepages: ['Jacquère', 'Mondeuse', 'Altesse'],
    longevites: {
      'white': AgingProfile(id: 'savoie_blanc', libelle: 'Savoie blanc',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
      'red': AgingProfile(id: 'savoie_rouge', libelle: 'Mondeuse',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
    },
  ),

  // ═══════════════ SUD-OUEST ═══════════════
  RegionVin(
    id: 'fr_sud_ouest',
    pays: 'France',
    nom: 'Madiran, Cahors & Irouléguy',
    elevages: {'red': Elevage(ContenantElevage.barrique, 14)},
    alias: ['madiran', 'cahors', 'irouleguy'],
    cepages: ['Tannat', 'Malbec', 'Fer Servadou', 'Négrette'],
    longevites: {
      'red': AgingProfile(id: 'sud_ouest_rouge', libelle: 'Madiran & Cahors',
          debut: 3, picDebut: 5, picFin: 11, fin: 15),
      'white': AgingProfile(id: 'sud_ouest_blanc', libelle: 'Sud-Ouest blanc',
          debut: 1, picDebut: 2, picFin: 6, fin: 9),
    },
    references: [
      ReferenceVin(nom: 'Château Montus', alias: ['montus']),
      ReferenceVin(nom: 'Clos Triguedina'),
    ],
  ),
  RegionVin(
    id: 'fr_sud_ouest_fruite',
    pays: 'France',
    nom: 'Sud-Ouest',
    alias: ['fronton', 'gaillac', 'bergerac', 'pecharmant', 'marcillac', 'saint-mont',
      'buzet', 'cotes de gascogne', 'marmandais', 'duras'],
    cepages: ['Négrette', 'Fer Servadou', 'Merlot', 'Colombard'],
    longevites: {
      'red': AgingProfile(id: 'sud_ouest_fruite', libelle: 'Sud-Ouest rouge',
          debut: 1, picDebut: 2, picFin: 5, fin: 8),
      'white': AgingProfile(id: 'sud_ouest_fruite_blanc', libelle: 'Sud-Ouest blanc',
          debut: 0, picDebut: 1, picFin: 2, fin: 4),
    },
  ),
  RegionVin(
    id: 'fr_jurancon',
    pays: 'France',
    nom: 'Jurançon & Pacherenc',
    alias: ['jurancon', 'pacherenc'],
    cepages: ['Petit Manseng', 'Gros Manseng'],
    longevites: {
      'sweet': AgingProfile(id: 'jurancon_moelleux', libelle: 'Jurançon moelleux',
          debut: 3, picDebut: 8, picFin: 25, fin: 40),
      'white': AgingProfile(id: 'jurancon_sec', libelle: 'Jurançon sec',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
    },
  ),

  // ═══════════════ CHAMPAGNE & EFFERVESCENTS ═══════════════
  RegionVin(
    id: 'fr_champagne',
    pays: 'France',
    nom: 'Champagne',
    elevages: {'*': Elevage(ContenantElevage.bouteille, 15, impose: true)},
    alias: ['champagne'],
    cepages: ['Chardonnay', 'Pinot Noir', 'Pinot Meunier'],
    longevites: {'*': AgingProfile(id: 'champagne_millesime', libelle: 'Champagne',
        debut: 2, picDebut: 5, picFin: 14, fin: 20)},
    references: [
      ReferenceVin(nom: 'Krug', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'krug', libelle: 'Krug',
              debut: 5, picDebut: 12, picFin: 35, fin: 50),
          elevage: Elevage(ContenantElevage.bouteille, 84)),
      ReferenceVin(nom: 'Dom Pérignon', alias: ['dom perignon'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'dom_perignon', libelle: 'Dom Pérignon',
              debut: 5, picDebut: 12, picFin: 30, fin: 45),
          elevage: Elevage(ContenantElevage.bouteille, 96)),
      ReferenceVin(nom: 'Salon'),
      ReferenceVin(nom: 'Bollinger', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Louis Roederer', alias: ['cristal']),
      ReferenceVin(nom: 'Pol Roger', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Veuve Clicquot', raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Moët & Chandon', alias: ['moet et chandon', 'moet'],
          raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Piper-Heidsieck', alias: ['piper heidsieck'],
          raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Laurent-Perrier', raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Taittinger', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'fr_cremants',
    pays: 'France',
    nom: 'Crémants & mousseux',
    elevages: {'*': Elevage(ContenantElevage.bouteille, 9, impose: true)},
    alias: ['cremant', 'cremant de loire', 'cremant de bourgogne',
      'cremant de limoux', 'blanquette', 'vin mousseux', 'cremant de bordeaux'],
    longevites: {'*': AgingProfile(id: 'cremant', libelle: 'Crémant',
        debut: 0, picDebut: 1, picFin: 4, fin: 6)},
  ),
];
