import 'wine_world_model.dart';

/// États-Unis, Argentine, Chili, Australie, Nouvelle-Zélande, Afrique du Sud.
///
/// C'est ici que se concentre le VOLUME scanné : un Marlborough Sauvignon ou un
/// Casillero del Diablo passent devant l'appareil bien plus souvent qu'un Pétrus. Se
/// tromper d'un an sur eux se produit des milliers de fois.
const List<RegionVin> regionsNouveauMonde = [
  // ═══════════════ ÉTATS-UNIS ═══════════════
  RegionVin(
    id: 'us_napa',
    pays: 'États-Unis',
    nom: 'Napa Valley',
    elevages: {'red': Elevage(ContenantElevage.barrique, 20)},
    alias: ['napa', 'oakville', 'rutherford', 'stags leap', 'howell mountain',
      'st helena', 'calistoga', 'spring mountain', 'diamond mountain'],
    cepages: ['Cabernet Sauvignon', 'Merlot'],
    longevites: {
      'red': AgingProfile(id: 'napa_rouge', libelle: 'Napa rouge',
          debut: 4, picDebut: 8, picFin: 18, fin: 26),
      'white': AgingProfile(id: 'napa_blanc', libelle: 'Napa blanc',
          debut: 1, picDebut: 3, picFin: 9, fin: 13),
    },
    references: [
      ReferenceVin(nom: 'Screaming Eagle', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'screaming_eagle', libelle: 'Screaming Eagle',
              debut: 6, picDebut: 12, picFin: 30, fin: 45)),
      ReferenceVin(nom: 'Opus One', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'opus_one', libelle: 'Opus One',
              debut: 5, picDebut: 10, picFin: 28, fin: 40),
          elevage: Elevage(ContenantElevage.barrique, 18)),
      ReferenceVin(nom: 'Harlan Estate'),
      ReferenceVin(nom: 'Dominus'),
      ReferenceVin(nom: 'Ridge', alias: ['monte bello']),
      ReferenceVin(nom: 'Caymus', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Robert Mondavi', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Stag\'s Leap Wine Cellars', alias: ['stags leap wine cellars']),
    ],
  ),
  RegionVin(
    id: 'us_sonoma',
    pays: 'États-Unis',
    nom: 'Sonoma & côte californienne',
    elevages: {'red': Elevage(ContenantElevage.barrique, 14),
      'white': Elevage(ContenantElevage.barrique, 10)},
    alias: ['sonoma', 'russian river', 'alexander valley', 'dry creek',
      'carneros', 'anderson valley', 'santa barbara', 'sta rita hills',
      'paso robles', 'monterey'],
    cepages: ['Pinot Noir', 'Chardonnay', 'Zinfandel'],
    longevites: {
      'red': AgingProfile(id: 'sonoma_rouge', libelle: 'Sonoma rouge',
          debut: 2, picDebut: 5, picFin: 13, fin: 18),
      'white': AgingProfile(id: 'sonoma_blanc', libelle: 'Sonoma blanc',
          debut: 1, picDebut: 3, picFin: 9, fin: 13),
    },
    references: [
      ReferenceVin(nom: 'Kistler'),
      ReferenceVin(nom: 'Williams Selyem'),
      ReferenceVin(nom: 'Kendall-Jackson', alias: ['kendall jackson'],
          raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Barefoot', raison: RaisonDePresence.grandVolume,
          longevite: AgingProfile(id: 'barefoot', libelle: 'Barefoot',
              debut: 0, picDebut: 0, picFin: 2, fin: 3)),
      ReferenceVin(nom: 'Gallo', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'us_oregon_washington',
    pays: 'États-Unis',
    nom: 'Oregon & Washington',
    alias: ['willamette', 'oregon', 'columbia valley', 'walla walla',
      'yakima', 'red mountain', 'washington'],
    cepages: ['Pinot Noir', 'Cabernet Sauvignon', 'Syrah'],
    longevites: {
      'red': AgingProfile(id: 'pnw_rouge', libelle: 'Rouge du Nord-Ouest',
          debut: 2, picDebut: 5, picFin: 14, fin: 20),
      'white': AgingProfile(id: 'pnw_blanc', libelle: 'Blanc du Nord-Ouest',
          debut: 1, picDebut: 2, picFin: 8, fin: 12),
    },
    references: [
      ReferenceVin(nom: 'Domaine Drouhin Oregon'),
      ReferenceVin(nom: 'Quilceda Creek'),
      ReferenceVin(nom: 'Chateau Ste. Michelle', raison: RaisonDePresence.grandVolume),
    ],
  ),

  // ═══════════════ ARGENTINE ═══════════════
  RegionVin(
    id: 'ar_mendoza',
    pays: 'Argentine',
    nom: 'Mendoza',
    elevages: {'red': Elevage(ContenantElevage.barrique, 14)},
    alias: ['mendoza', 'uco', 'lujan de cuyo', 'maipu', 'gualtallary',
      'valle de uco'],
    cepages: ['Malbec', 'Cabernet Sauvignon', 'Bonarda'],
    longevites: {
      'red': AgingProfile(id: 'mendoza_rouge', libelle: 'Mendoza rouge',
          debut: 2, picDebut: 5, picFin: 13, fin: 18),
      'white': AgingProfile(id: 'mendoza_blanc', libelle: 'Mendoza blanc',
          debut: 1, picDebut: 2, picFin: 6, fin: 9),
    },
    references: [
      ReferenceVin(nom: 'Catena Zapata', alias: ['catena'],
          raison: RaisonDePresence.lesDeux, certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'catena_zapata', libelle: 'Catena Zapata',
              debut: 4, picDebut: 8, picFin: 20, fin: 28)),
      ReferenceVin(nom: 'Achaval-Ferrer', alias: ['achaval ferrer']),
      ReferenceVin(nom: 'Zuccardi'),
      ReferenceVin(nom: 'Trapiche', raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Norton', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'ar_salta',
    pays: 'Argentine',
    nom: 'Salta & Patagonie',
    alias: ['salta', 'cafayate', 'patagonia', 'rio negro', 'neuquen'],
    cepages: ['Torrontés', 'Malbec', 'Pinot Noir'],
    longevites: {
      'red': AgingProfile(id: 'ar_nord_sud_rouge', libelle: 'Salta & Patagonie rouge',
          debut: 2, picDebut: 4, picFin: 11, fin: 16),
      'white': AgingProfile(id: 'torrontes', libelle: 'Torrontés',
          debut: 0, picDebut: 1, picFin: 3, fin: 5),
    },
    references: [ReferenceVin(nom: 'Colomé')],
  ),

  // ═══════════════ CHILI ═══════════════
  RegionVin(
    id: 'cl_maipo',
    pays: 'Chili',
    nom: 'Maipo & Cachapoal',
    elevages: {'red': Elevage(ContenantElevage.barrique, 16)},
    alias: ['maipo', 'cachapoal', 'puente alto', 'alto maipo'],
    cepages: ['Cabernet Sauvignon', 'Carménère'],
    longevites: {'red': AgingProfile(id: 'maipo', libelle: 'Maipo',
        debut: 3, picDebut: 6, picFin: 15, fin: 20)},
    references: [
      ReferenceVin(nom: 'Almaviva', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'almaviva', libelle: 'Almaviva',
              debut: 5, picDebut: 10, picFin: 25, fin: 35),
          elevage: Elevage(ContenantElevage.barrique, 18)),
      ReferenceVin(nom: 'Don Melchor',
          longevite: AgingProfile(id: 'don_melchor', libelle: 'Don Melchor',
              debut: 5, picDebut: 10, picFin: 25, fin: 35)),
      ReferenceVin(nom: 'Viña Errázuriz', alias: ['errazuriz', 'sena']),
      ReferenceVin(nom: 'Concha y Toro', alias: ['casillero del diablo'],
          raison: RaisonDePresence.grandVolume,
          longevite: AgingProfile(id: 'casillero', libelle: 'Casillero del Diablo',
              debut: 0, picDebut: 2, picFin: 5, fin: 8)),
      ReferenceVin(nom: 'Santa Rita', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'cl_colchagua',
    pays: 'Chili',
    nom: 'Colchagua & Apalta',
    elevages: {'red': Elevage(ContenantElevage.barrique, 14)},
    alias: ['colchagua', 'apalta', 'rapel', 'central valley', 'valle central',
      'curico', 'maule'],
    cepages: ['Carménère', 'Cabernet Sauvignon', 'Syrah'],
    longevites: {'red': AgingProfile(id: 'colchagua', libelle: 'Colchagua',
        debut: 2, picDebut: 5, picFin: 13, fin: 18)},
    references: [
      ReferenceVin(nom: 'Clos Apalta', alias: ['lapostolle']),
      ReferenceVin(nom: 'Montes', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Santa Ema', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'cl_cotier',
    pays: 'Chili',
    nom: 'Chili côtier & nord',
    elevages: {'white': Elevage(ContenantElevage.inox, 6)},
    alias: ['casablanca', 'san antonio', 'leyda', 'limari', 'elqui',
      'aconcagua', 'itata', 'bio bio'],
    cepages: ['Sauvignon Blanc', 'Chardonnay', 'Pinot Noir', 'Syrah'],
    longevites: {
      'white': AgingProfile(id: 'cl_blanc', libelle: 'Blanc chilien côtier',
          debut: 0, picDebut: 1, picFin: 5, fin: 8),
      'red': AgingProfile(id: 'cl_cotier_rouge', libelle: 'Rouge chilien côtier',
          debut: 2, picDebut: 4, picFin: 11, fin: 16),
    },
  ),

  // ═══════════════ AUSTRALIE ═══════════════
  RegionVin(
    id: 'au_barossa',
    pays: 'Australie',
    nom: 'Barossa, Eden & Clare',
    elevages: {'red': Elevage(ContenantElevage.barrique, 18)},
    alias: ['barossa', 'eden valley', 'clare valley'],
    cepages: ['Shiraz', 'Riesling', 'Grenache'],
    longevites: {
      'red': AgingProfile(id: 'barossa', libelle: 'Barossa Shiraz',
          debut: 3, picDebut: 7, picFin: 18, fin: 25),
      'white': AgingProfile(id: 'clare_riesling', libelle: 'Riesling de Clare',
          debut: 1, picDebut: 4, picFin: 14, fin: 20),
    },
    references: [
      ReferenceVin(nom: 'Penfolds Grange', alias: ['grange'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'grange', libelle: 'Penfolds Grange',
              debut: 8, picDebut: 15, picFin: 40, fin: 60),
          elevage: Elevage(ContenantElevage.barrique, 18)),
      ReferenceVin(nom: 'Henschke', certitude: Certitude.verifiee, alias: ['hill of grace'],
          longevite: AgingProfile(id: 'hill_of_grace', libelle: 'Hill of Grace',
              debut: 6, picDebut: 12, picFin: 30, fin: 50)),
      ReferenceVin(nom: 'Torbreck'),
      ReferenceVin(nom: 'Penfolds', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Jacob\'s Creek', alias: ['jacobs creek'],
          raison: RaisonDePresence.grandVolume,
          longevite: AgingProfile(id: 'jacobs_creek', libelle: 'Jacob\'s Creek',
              debut: 0, picDebut: 1, picFin: 4, fin: 6)),
      ReferenceVin(nom: 'Yellow Tail', raison: RaisonDePresence.grandVolume,
          longevite: AgingProfile(id: 'yellow_tail', libelle: 'Yellow Tail',
              debut: 0, picDebut: 0, picFin: 2, fin: 3)),
    ],
  ),
  RegionVin(
    id: 'au_coonawarra',
    pays: 'Australie',
    nom: 'Coonawarra, McLaren Vale & Sud',
    alias: ['coonawarra', 'mclaren vale', 'adelaide hills', 'langhorne creek',
      'padthaway'],
    cepages: ['Cabernet Sauvignon', 'Shiraz'],
    longevites: {'red': AgingProfile(id: 'coonawarra', libelle: 'Coonawarra & McLaren',
        debut: 3, picDebut: 6, picFin: 16, fin: 22)},
    references: [
      ReferenceVin(nom: 'Wynns Coonawarra', alias: ['wynns']),
      ReferenceVin(nom: 'd\'Arenberg', alias: ['darenberg']),
    ],
  ),
  RegionVin(
    id: 'au_margaret_victoria',
    pays: 'Australie',
    nom: 'Margaret River, Victoria & Hunter',
    alias: ['margaret river', 'yarra valley', 'mornington', 'hunter valley',
      'geelong', 'heathcote', 'grampians', 'tasmania'],
    cepages: ['Chardonnay', 'Cabernet Sauvignon', 'Pinot Noir', 'Semillon'],
    longevites: {
      'red': AgingProfile(id: 'au_est_rouge', libelle: 'Rouge de l\'Est australien',
          debut: 2, picDebut: 5, picFin: 14, fin: 20),
      'white': AgingProfile(id: 'au_est_blanc', libelle: 'Blanc australien',
          debut: 1, picDebut: 3, picFin: 10, fin: 15),
    },
    references: [
      ReferenceVin(nom: 'Leeuwin Estate'),
      ReferenceVin(nom: 'Cullen'),
      ReferenceVin(nom: 'Vasse Felix'),
    ],
  ),
  RegionVin(
    id: 'au_generique',
    pays: 'Australie',
    nom: 'Australie — mentions larges',
    elevages: {'*': Elevage(ContenantElevage.inox, 6)},
    alias: ['south australia', 'south eastern australia', 'western australia',
      'victoria', 'new south wales'],
    cepages: ['Shiraz', 'Chardonnay'],
    longevites: {
      'red': AgingProfile(id: 'au_generique_rouge', libelle: 'Rouge australien',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
      'white': AgingProfile(id: 'au_generique_blanc', libelle: 'Blanc australien',
          debut: 0, picDebut: 1, picFin: 4, fin: 7),
    },
    references: [
      ReferenceVin(nom: 'Koonunga Hill', raison: RaisonDePresence.grandVolume,
          longevite: AgingProfile(id: 'koonunga', libelle: 'Koonunga Hill',
              debut: 1, picDebut: 3, picFin: 7, fin: 10)),
      ReferenceVin(nom: 'Hardys', raison: RaisonDePresence.grandVolume),
    ],
  ),

  // ═══════════════ NOUVELLE-ZÉLANDE ═══════════════
  RegionVin(
    id: 'nz_marlborough',
    pays: 'Nouvelle-Zélande',
    nom: 'Marlborough',
    elevages: {'white': Elevage(ContenantElevage.inox, 4)},
    alias: ['marlborough', 'awatere', 'wairau'],
    cepages: ['Sauvignon Blanc', 'Pinot Noir'],
    longevites: {
      'white': AgingProfile(id: 'marlborough_sb', libelle: 'Sauvignon de Marlborough',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
      'red': AgingProfile(id: 'marlborough_pn', libelle: 'Pinot de Marlborough',
          debut: 1, picDebut: 3, picFin: 9, fin: 13),
    },
    references: [
      ReferenceVin(nom: 'Cloudy Bay', raison: RaisonDePresence.lesDeux,
          elevage: Elevage(ContenantElevage.inox, 4)),
      ReferenceVin(nom: 'Greywacke'),
      ReferenceVin(nom: 'Seresin Estate'),
      ReferenceVin(nom: 'Oyster Bay', raison: RaisonDePresence.grandVolume),
      ReferenceVin(nom: 'Villa Maria', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'nz_otago',
    pays: 'Nouvelle-Zélande',
    nom: 'Central Otago, Hawke\'s Bay & Martinborough',
    alias: ['central otago', 'hawkes bay', 'martinborough', 'wairarapa',
      'gimblett gravels', 'nelson', 'waipara'],
    cepages: ['Pinot Noir', 'Syrah', 'Chardonnay'],
    longevites: {
      'red': AgingProfile(id: 'nz_rouge', libelle: 'Rouge néo-zélandais',
          debut: 2, picDebut: 4, picFin: 11, fin: 16),
      'white': AgingProfile(id: 'nz_blanc', libelle: 'Blanc néo-zélandais',
          debut: 1, picDebut: 2, picFin: 7, fin: 11),
    },
    references: [
      ReferenceVin(nom: 'Felton Road'),
      ReferenceVin(nom: 'Rippon'),
      ReferenceVin(nom: 'Craggy Range'),
    ],
  ),

  // ═══════════════ AFRIQUE DU SUD ═══════════════
  RegionVin(
    id: 'za_stellenbosch',
    pays: 'Afrique du Sud',
    nom: 'Stellenbosch & Paarl',
    elevages: {'red': Elevage(ContenantElevage.barrique, 16)},
    alias: ['stellenbosch', 'paarl', 'franschhoek', 'simonsberg',
      'helderberg'],
    cepages: ['Cabernet Sauvignon', 'Pinotage', 'Chenin Blanc'],
    longevites: {
      'red': AgingProfile(id: 'stellenbosch_rouge', libelle: 'Stellenbosch rouge',
          debut: 2, picDebut: 5, picFin: 14, fin: 20),
      'white': AgingProfile(id: 'za_chenin', libelle: 'Chenin sud-africain',
          debut: 1, picDebut: 3, picFin: 10, fin: 15),
    },
    references: [
      ReferenceVin(nom: 'Kanonkop'),
      ReferenceVin(nom: 'Meerlust'),
      ReferenceVin(nom: 'Rust en Vrede'),
      ReferenceVin(nom: 'KWV', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'za_swartland',
    pays: 'Afrique du Sud',
    nom: 'Swartland, Walker Bay & Cap',
    alias: ['swartland', 'walker bay', 'hemel-en-aarde', 'elgin',
      'constantia', 'robertson', 'western cape'],
    cepages: ['Syrah', 'Chenin Blanc', 'Pinot Noir'],
    longevites: {
      'red': AgingProfile(id: 'swartland_rouge', libelle: 'Swartland rouge',
          debut: 2, picDebut: 5, picFin: 13, fin: 18),
      'white': AgingProfile(id: 'cap_blanc', libelle: 'Blanc du Cap',
          debut: 1, picDebut: 2, picFin: 8, fin: 12),
      'sweet': AgingProfile(id: 'constantia', libelle: 'Vin de Constance',
          debut: 3, picDebut: 10, picFin: 30, fin: 50),
    },
    references: [
      ReferenceVin(nom: 'Sadie Family', alias: ['sadie']),
      ReferenceVin(nom: 'Klein Constantia', alias: ['vin de constance']),
      ReferenceVin(nom: 'Hamilton Russell'),
    ],
  ),
];
