import 'wine_world_model.dart';

/// Italie — le pays où la longévité est la plus mal estimée par défaut : un Barolo et un
/// Prosecco partagent une nationalité et rien d'autre.
const List<RegionVin> regionsItalie = [
  RegionVin(
    id: 'it_barolo',
    pays: 'Italie',
    nom: 'Barolo & Barbaresco',
    alias: ['barolo', 'barbaresco', 'langhe nebbiolo', 'roero'],
    cepages: ['Nebbiolo'],
    longevites: {'red': AgingProfile(id: 'barolo', libelle: 'Barolo',
        debut: 6, picDebut: 12, picFin: 25, fin: 35)},
    references: [
      ReferenceVin(nom: 'Giacomo Conterno', alias: ['conterno monfortino'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'monfortino', libelle: 'Monfortino',
              debut: 10, picDebut: 20, picFin: 45, fin: 60)),
      ReferenceVin(nom: 'Bruno Giacosa'),
      ReferenceVin(nom: 'Gaja', certitude: Certitude.verifiee),
      ReferenceVin(nom: 'Vietti'),
      ReferenceVin(nom: 'Bartolo Mascarello'),
      ReferenceVin(nom: 'Giuseppe Rinaldi'),
      ReferenceVin(nom: 'Pio Cesare'),
      ReferenceVin(nom: 'Fontanafredda', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'it_piemonte_autres',
    pays: 'Italie',
    nom: 'Piémont — Barbera, Dolcetto, Gavi',
    alias: ['barbera', 'dolcetto', 'gavi', 'alba', 'asti', 'moscato d\'asti',
      'gattinara', 'ghemme'],
    cepages: ['Barbera', 'Dolcetto', 'Cortese'],
    longevites: {
      'red': AgingProfile(id: 'piemonte_rouge', libelle: 'Piémont rouge',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
      'white': AgingProfile(id: 'gavi', libelle: 'Gavi',
          debut: 0, picDebut: 1, picFin: 4, fin: 6),
    },
  ),
  RegionVin(
    id: 'it_brunello',
    pays: 'Italie',
    nom: 'Montalcino',
    alias: ['brunello', 'montalcino', 'rosso di montalcino'],
    cepages: ['Sangiovese'],
    longevites: {'red': AgingProfile(id: 'brunello', libelle: 'Brunello',
        debut: 5, picDebut: 10, picFin: 22, fin: 32)},
    references: [
      ReferenceVin(nom: 'Biondi-Santi', alias: ['biondi santi'],
          certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'biondi_santi', libelle: 'Biondi-Santi',
              debut: 10, picDebut: 20, picFin: 45, fin: 60)),
      ReferenceVin(nom: 'Soldera'),
      ReferenceVin(nom: 'Casanova di Neri'),
      ReferenceVin(nom: 'Banfi', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_chianti',
    pays: 'Italie',
    nom: 'Chianti & Toscane centrale',
    alias: ['chianti', 'chianti classico', 'vino nobile', 'montepulciano',
      'carmignano', 'morellino'],
    cepages: ['Sangiovese'],
    longevites: {'red': AgingProfile(id: 'chianti', libelle: 'Chianti',
        debut: 2, picDebut: 5, picFin: 12, fin: 18)},
    references: [
      ReferenceVin(nom: 'Castello di Ama'),
      ReferenceVin(nom: 'Fontodi'),
      ReferenceVin(nom: 'Isole e Olena'),
      ReferenceVin(nom: 'Antinori', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Ruffino', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_bolgheri',
    pays: 'Italie',
    nom: 'Bolgheri & Maremme',
    alias: ['bolgheri', 'maremma', 'sassicaia', 'toscana igt'],
    cepages: ['Cabernet Sauvignon', 'Merlot', 'Cabernet Franc'],
    longevites: {'red': AgingProfile(id: 'bolgheri', libelle: 'Bolgheri',
        debut: 4, picDebut: 8, picFin: 20, fin: 28)},
    references: [
      ReferenceVin(nom: 'Sassicaia', certitude: Certitude.verifiee,
          longevite: AgingProfile(id: 'sassicaia', libelle: 'Sassicaia',
              debut: 6, picDebut: 12, picFin: 30, fin: 45)),
      ReferenceVin(nom: 'Ornellaia'),
      ReferenceVin(nom: 'Masseto',
          longevite: AgingProfile(id: 'masseto', libelle: 'Masseto',
              debut: 6, picDebut: 12, picFin: 30, fin: 45)),
      ReferenceVin(nom: 'Tignanello'),
    ],
  ),
  RegionVin(
    id: 'it_veneto',
    pays: 'Italie',
    nom: 'Vénétie — Amarone & Valpolicella',
    alias: ['amarone', 'valpolicella', 'ripasso', 'recioto', 'bardolino',
      'soave'],
    cepages: ['Corvina', 'Rondinella', 'Garganega'],
    longevites: {
      'red': AgingProfile(id: 'amarone', libelle: 'Amarone & Valpolicella',
          debut: 4, picDebut: 8, picFin: 20, fin: 28),
      'white': AgingProfile(id: 'soave', libelle: 'Soave',
          debut: 1, picDebut: 2, picFin: 6, fin: 9),
    },
    references: [
      ReferenceVin(nom: 'Giuseppe Quintarelli', alias: ['quintarelli']),
      ReferenceVin(nom: 'Dal Forno Romano', alias: ['dal forno']),
      ReferenceVin(nom: 'Masi', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_prosecco',
    pays: 'Italie',
    nom: 'Prosecco & effervescents italiens',
    alias: ['prosecco', 'valdobbiadene', 'conegliano', 'lambrusco',
      'franciacorta'],
    cepages: ['Glera'],
    longevites: {'*': AgingProfile(id: 'prosecco', libelle: 'Prosecco',
        debut: 0, picDebut: 0, picFin: 2, fin: 3)},
    references: [
      ReferenceVin(nom: 'Ca\' del Bosco', alias: ['ca del bosco'],
          longevite: AgingProfile(id: 'franciacorta', libelle: 'Franciacorta',
              debut: 1, picDebut: 3, picFin: 10, fin: 15)),
      ReferenceVin(nom: 'Bellavista'),
      ReferenceVin(nom: 'La Marca', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_aglianico',
    pays: 'Italie',
    nom: 'Campanie & Basilicate',
    alias: ['aglianico', 'taurasi', 'vulture', 'greco di tufo',
      'fiano di avellino', 'falanghina'],
    cepages: ['Aglianico', 'Fiano', 'Greco'],
    longevites: {
      'red': AgingProfile(id: 'aglianico', libelle: 'Aglianico',
          debut: 4, picDebut: 8, picFin: 18, fin: 25),
      'white': AgingProfile(id: 'fiano', libelle: 'Fiano & Greco',
          debut: 1, picDebut: 3, picFin: 8, fin: 12),
    },
    references: [
      ReferenceVin(nom: 'Mastroberardino'),
      ReferenceVin(nom: 'Cantine del Notaio'),
    ],
  ),
  RegionVin(
    id: 'it_sicile',
    pays: 'Italie',
    nom: 'Sicile & Etna',
    alias: ['etna', 'sicilia', 'nero d\'avola', 'cerasuolo di vittoria',
      'marsala'],
    cepages: ['Nerello Mascalese', 'Nero d\'Avola', 'Carricante'],
    longevites: {
      'red': AgingProfile(id: 'etna_rouge', libelle: 'Etna & Sicile rouge',
          debut: 2, picDebut: 5, picFin: 14, fin: 20),
      'white': AgingProfile(id: 'etna_blanc', libelle: 'Etna blanc',
          debut: 1, picDebut: 3, picFin: 9, fin: 14),
      'fortified': AgingProfile(id: 'marsala', libelle: 'Marsala',
          debut: 1, picDebut: 5, picFin: 25, fin: 40),
    },
    references: [
      ReferenceVin(nom: 'Passopisciaro'),
      ReferenceVin(nom: 'Planeta', raison: RaisonDePresence.lesDeux),
      ReferenceVin(nom: 'Donnafugata', raison: RaisonDePresence.lesDeux),
    ],
  ),
  RegionVin(
    id: 'it_pouilles',
    pays: 'Italie',
    nom: 'Pouilles & Sud',
    alias: ['puglia', 'primitivo', 'salice salentino', 'negroamaro',
      'manduria'],
    cepages: ['Primitivo', 'Negroamaro'],
    longevites: {'red': AgingProfile(id: 'primitivo', libelle: 'Primitivo',
        debut: 1, picDebut: 3, picFin: 8, fin: 12)},
  ),
  RegionVin(
    id: 'it_nord_est',
    pays: 'Italie',
    nom: 'Nord-Est — Frioul, Trentin, Haut-Adige',
    alias: ['friuli', 'collio', 'alto adige', 'trentino', 'sudtirol',
      'pinot grigio'],
    cepages: ['Pinot Grigio', 'Friulano', 'Lagrein'],
    longevites: {
      'white': AgingProfile(id: 'nord_est_blanc', libelle: 'Blanc du Nord-Est',
          debut: 1, picDebut: 2, picFin: 7, fin: 11),
      'red': AgingProfile(id: 'nord_est_rouge', libelle: 'Rouge du Nord-Est',
          debut: 1, picDebut: 3, picFin: 9, fin: 13),
    },
    references: [
      ReferenceVin(nom: 'Jermann'),
      ReferenceVin(nom: 'Santa Margherita', raison: RaisonDePresence.grandVolume),
    ],
  ),
  RegionVin(
    id: 'it_abruzzes',
    pays: 'Italie',
    nom: 'Abruzzes & Marches',
    alias: ['montepulciano d\'abruzzo', 'trebbiano d\'abruzzo', 'verdicchio',
      'rosso conero'],
    cepages: ['Montepulciano', 'Verdicchio'],
    longevites: {
      'red': AgingProfile(id: 'abruzzo_rouge', libelle: 'Montepulciano d\'Abruzzo',
          debut: 1, picDebut: 3, picFin: 9, fin: 14),
      'white': AgingProfile(id: 'verdicchio', libelle: 'Verdicchio',
          debut: 1, picDebut: 2, picFin: 7, fin: 11),
    },
    references: [
      ReferenceVin(nom: 'Emidio Pepe',
          longevite: AgingProfile(id: 'emidio_pepe', libelle: 'Emidio Pepe',
              debut: 5, picDebut: 12, picFin: 30, fin: 45)),
      ReferenceVin(nom: 'Valentini'),
    ],
  ),
];
